#!/bin/bash -f

EXECPATH=.

pid=$$
host=`hostname`


if [ ! "$TMPDIR" ] ; then
    export TMPDIR="/var/tmp"
fi

tmpfile=$TMPDIR/"eproof_"${host}"_"${pid}
tmpfile2=$TMPDIR/"eprooftmp_"${host}"_"${pid}

timeout=""



cleanup () 
{  
    touch $tmpfile $tmpfile2
    rm $tmpfile $tmpfile2
    if [ "$timeout" = "" ] ; then
	echo "# Terminated by signal or interrupt, cleaning up"
    fi
    exit 
} 

trap 'cleanup' EXIT

cat /dev/null > $tmpfile 
cat /dev/null > $tmpfile2 

searchlimit=2000000000 # Effectively unlimited
prooflimit=2000000000
timelimit=2000000000
outfile=""

print_tail=0
newargs=""
format=""

for argument in  $*; do
    if [ "$argument" = "-R" -o "$argument" = "--resources-info" -o "$argument" = "--print-statistics" ] ; then
	print_tail=29
    else
	head=`echo "$argument"|cut -d= -f1`
	if [ "$head" = "--cpu-limit" ] ; then
	    timelimit=`echo $argument|cut -d= -f2`
            argument=""
	fi    
	if [ "$head" = "-o" ] ; then
	    echo "Short option -o not supported by eproof, use --output-file=<file>"
	    exit 1
	fi    
	if [ "$head" = "--output-file" ] ; then
	    outfile=`echo $argument|cut -d= -f2`
	    cat /dev/null > $outfile
	    argument=""
	fi
	if  [ "$argument" = "--tstp-out" ] ; then
	    argument=""
	    format="--tstp-out"
	fi
    fi
    newargs=$newargs" "$argument
done

$EXECPATH/eprover $newargs -l4 -R -o- --pcl-terms-compressed --pcl-compact> $tmpfile
tail -60 $tmpfile > $tmpfile2
searchtime=`cat $tmpfile2|grep "Total time"|cut -d: -f2|sed -e 's/[s ]//g'|cut -d. -f1`
if [ "$searchtime" ]; then
    statusline=`grep -c 'No proof found!' $tmpfile2`
    if [ "$statusline" = "1" ] ; then
        echo "# Problem is satisfiable, generating saturation derivation"
    else
	statusline=`grep -c 'Proof found!' $tmpfile2`
        if [ "$statusline" = "1" ] ; then
            echo "# Problem is unsatisfiable, constructing proof object"
	else
	    statusline=`grep -c 'Watchlist is empty!' $tmpfile2`
	    if [ "$statusline" = "1" ] ; then
		echo "# All watchlist clauses generated, constructing derivation"
	    else
		echo "# Cannot determine problem status"
		exit 1
	    fi
	fi
    fi
    prooflimit=`expr $timelimit - $searchtime - 1`
    ulimit -S -t $prooflimit 2>&1> /dev/null
    if [ "$outfile" ]; then
	exec 1> "$outfile"
    fi
    grep "# TSTP exit status" $tmpfile2
    grep "# Failure"          $tmpfile2
    $EXECPATH/epclextract $format -f --competition-framing $tmpfile
    tail -$print_tail $tmpfile2
else
    echo "# Cannot determine problem status within resource limit"
fi

timeout="1"



