#!/bin/bash -f

EXECPATH=~/bin

pid=$$
host=`hostname`


if [ ! "$TMPDIR" ] ; then
    export TMPDIR="/var/tmp"
fi

tmpfile=$TMPDIR/"eproof_"${host}"_"${pid}
tmpfile2=$TMPDIR/"eprooftmp_"${host}"_"${pid}
touch tmpfile tmpfile2

timeout=""

cleanup () 
{     
    rm $tmpfile
    if [ "$timeout" = "" ] ; then
	echo "# Terminated by signal or interrupt, cleaning up"
    fi
    exit 
} 

trap 'cleanup' EXIT

searchlimit=2000000000 # Effectively unlimited
prooflimit=2000000000
timelimit=2000000000
outfile=""

for argument in  $*; do
    head=`echo "$argument"|cut -d= -f1`
    if [ "$head" = "--cpu-limit" ] ; then
    	timelimit=`echo $argument|cut -d= -f2`
    fi    
    if [ "$head" = "-o" ] ; then
    	echo "Short option -o not supported by eproof, use --output-file=<file>"
	exit 1
    fi    
    if [ "$head" = "--output-file" ] ; then
	outfile=`echo $argument|cut -d= -f2`
	cat /dev/null > $outfile
    	#outputoption="--output-file="$outfile
    fi    
done

$EXECPATH/eprover $* -l4 -R -o- --pcl-terms-compressed > $tmpfile
#$EXECPATH/eprover $* -l4 -R -o- > $tmpfile
tail -40 $tmpfile > $tmpfile2
searchtime=`cat $tmpfile2|grep "Total time"|cut -d: -f2|sed -e's/[s ]//g'|cut -d. -f1`
if [ "$searchtime" ]; then
    statusline=`grep -c 'No proof found!' $tmpfile`
    if [ "$statusline" = "1" ] ; then
        echo "# Problem is satisfiable, generating saturation derivation"
    else
	statusline=`grep -c 'Proof found!' $tmpfile`
        if [ "$statusline" = "1" ] ; then
            echo "# Problem is unsatisfiable, constructing proof object"
	else
	    echo "# Cannot determine problem status"
	    exit 1
	fi
    fi
    prooflimit=`expr $timelimit - $searchtime - 1`
    ulimit -S -t $prooflimit
    if  [ "$outfile" = "" ] ; then
	grep "# Proof found!" $tmpfile2
	grep "# No proof found!" $tmpfile2
	grep "# Failure" $tmpfile2
	$EXECPATH/epclextract -f --competition-framing $tmpfile
    else 
	grep "# Proof found!" $tmpfile2 >> $outfile
	grep "# No proof found!" $tmpfile2 >> $outfile
	grep "# Failure" $tmpfile2 >> $outfile
	$EXECPATH/epclextract -f --competition-framing $tmpfile >> $outfile
    fi
else
    echo "# Cannot determine problem status within resource limit"
fi
timeout="1"



