#!/bin/sh


if [ "$1" != "" ]
then
    INFO=$1
else
    INFO="No information given"
fi

echo "Testrun from `date` on `hostname`" $INFO ":" >> mini-result
for file in BOO001-1+rm_eq_rstfp.lop BOO007-2+rm_eq_rstfp.lop GRP119-1+rm_eq_rstfp.lop LUSK3.lop GROUP.lop
do 
    echo "========" >>  mini-result
    echo $file >> mini-result
    (time ./eprover -s $file) >> mini-result 2>&1
done
echo "====================" >> mini-result
