%------------------------------------------------------------------------------
% File     : CSR036+2 : TPTP v6.4.0. Released v3.4.0.
% Domain   : Common Sense Reasoning
% Problem  : Autogenerated Cyc Problem CSR036+2
% Version  : Especial.
% English  :

% Refs     : [RS+]   Reagan Smith et al., The Cyc TPTP Challenge Problem
% Source   : [RS+]
% Names    :

% Status   : Theorem
% Rating   : 0.14 v6.4.0, 0.07 v6.3.0, 0.15 v6.2.0, 0.18 v6.1.0, 0.32 v6.0.0, 0.25 v5.5.0, 0.38 v5.4.0, 0.30 v5.3.0, 0.39 v5.2.0, 0.21 v5.1.0, 0.29 v5.0.0, 0.30 v4.1.0, 0.39 v4.0.1, 0.47 v4.0.0, 0.45 v3.7.0, 0.14 v3.5.0, 0.25 v3.4.0
% Syntax   : Number of formulae    : 1132 ( 346 unit)
%            Number of atoms       : 1966 (   0 equality)
%            Maximal formula depth :    7 (   3 average)
%            Number of connectives :  843 (   9 ~  ;   0  |;  54  &)
%                                         (   0 <=>; 780 =>;   0 <=)
%                                         (   0 <~>;   0 ~|;   0 ~&)
%            Number of predicates  :  269 (   0 propositional; 1-3 arity)
%            Number of functors    :  413 ( 396 constant; 0-4 arity)
%            Number of variables   : 1121 (   0 singleton;1121 !;   0 ?)
%            Maximal term depth    :    4 (   1 average)
% SPC      : FOF_THM_RFO_NEQ

% Comments : Autogenerated from the OpenCyc KB. Documentation can be found at
%            http://opencyc.org/doc/#TPTP_Challenge_Problem_Set
%          : Cyc(R) Knowledge Base Copyright(C) 1995-2007 Cycorp, Inc., Austin,
%            TX, USA. All rights reserved.
%          : OpenCyc Knowledge Base Copyright(C) 2001-2007 Cycorp, Inc.,
%            Austin, TX, USA. All rights reserved.
%------------------------------------------------------------------------------
%$problem_series(cyc_scaling_2,[CSR025+2,CSR026+2,CSR027+2,CSR028+2,CSR029+2,CSR030+2,CSR031+2,CSR032+2,CSR033+2,CSR034+2,CSR035+2,CSR036+2,CSR037+2,CSR038+2,CSR039+2,CSR040+2,CSR041+2,CSR042+2,CSR043+2,CSR044+2,CSR045+2,CSR046+2,CSR047+2,CSR048+2,CSR049+2,CSR050+2,CSR051+2,CSR052+2,CSR053+2,CSR054+2,CSR055+2,CSR056+2,CSR057+2,CSR058+2,CSR059+2,CSR060+2,CSR061+2,CSR062+2,CSR063+2,CSR064+2,CSR065+2,CSR066+2,CSR067+2,CSR068+2,CSR069+2,CSR070+2,CSR071+2,CSR072+2,CSR073+2,CSR074+2])
%$static(cyc_scaling_2,include('Axioms/CSR002+1.ax'))
include('Axioms/CSR002+1.ax').
%------------------------------------------------------------------------------
fof(query86,conjecture,
    ( mtvisible(c_tptp_member974_mt)
   => disjointwith(c_tptpcol_15_22076,c_tptpcol_16_72795) )).

%------------------------------------------------------------------------------
