%------------------------------------------------------------------------------
% File     : SWW469^1 : TPTP v7.0.0. Released v5.3.0.
% Domain   : Software Verification
% Problem  : Hoare's Logic with Procedures line 112, 100 axioms selected
% Version  : Especial.
% English  :

% Refs     : [BN10]  Boehme & Nipkow (2010), Sledgehammer: Judgement Day
%          : [Bla11] Blanchette (2011), Email to Geoff Sutcliffe
% Source   : [Bla11]
% Names    : hoare_100_thf_l112 [Bla11]

% Status   : Theorem
% Rating   : 0.12 v7.0.0, 0.00 v6.2.0, 0.14 v5.5.0, 0.17 v5.4.0, 0.20 v5.3.0
% Syntax   : Number of formulae    :   10 (   4 unit;   4 type;   0 defn)
%            Number of atoms       :   11 (   2 equality;   4 variable)
%            Maximal formula depth :    6 (   2 average)
%            Number of connectives :    4 (   3   ~;   0   |;   0   &;   0   @)
%                                         (   1 <=>;   0  =>;   0  <=;   0 <~>)
%                                         (   0  ~|;   0  ~&)
%            Number of type conns  :    0 (   0   >;   0   *;   0   +;   0  <<)
%            Number of symbols     :    6 (   4   :;   0   =)
%            Number of variables   :    4 (   0 sgn;   2   !;   2   ?;   0   ^)
%                                         (   4   :;   0  !>;   0  ?*)
%                                         (   0  @-;   0  @+)
% SPC      : TH0_THM_EQU_NAR

% Comments : This file was generated by Isabelle (most likely Sledgehammer)
%            2011-08-09 18:59:06
%------------------------------------------------------------------------------
%----Should-be-implicit typings (1)
thf(ty_ty_tc__Com__Ostate,type,(
    state: $tType )).

%----Explicit typings (3)
thf(sy_c_HOL_Oinduct__false,type,(
    induct_false: $o )).

thf(sy_c_HOL_Oinduct__true,type,(
    induct_true: $o )).

thf(sy_c_Hoare__Mirabelle__ghhkfsbqqq_Ostate__not__singleton,type,(
    hoare_1821564147gleton: $o )).

%----Relevant facts (4)
thf(fact_0_state__not__singleton__def,axiom,
    ( hoare_1821564147gleton
  <=> ? [S: state,T: state] : ( S != T ) )).

thf(fact_1_induct__false__def,axiom,(
    ~ ( induct_false ) )).

thf(fact_2_induct__trueI,axiom,(
    induct_true )).

thf(fact_3_induct__true__def,axiom,(
    induct_true )).

%----Conjectures (2)
thf(conj_0,hypothesis,(
    hoare_1821564147gleton )).

thf(conj_1,conjecture,(
    ! [T: state] :
      ~ ( ! [S: state] : ( S = T ) ) )).

%------------------------------------------------------------------------------
