%------------------------------------------------------------------------------
% File     : SWW477^1 : TPTP v7.0.0. Released v5.3.0.
% Domain   : Software Verification
% Problem  : Java type soundness line 346, 100 axioms selected
% Version  : Especial.
% English  :

% Refs     : [BN10]  Boehme & Nipkow (2010), Sledgehammer: Judgement Day
%          : [Bla11] Blanchette (2011), Email to Geoff Sutcliffe
% Source   : [Bla11]
% Names    : jinja_100_thf_l346 [Bla11]

% Status   : Theorem
% Rating   : 1.00 v5.3.0
% Syntax   : Number of formulae    :  230 (   0 unit;  67 type;   0 defn)
%            Number of atoms       : 2411 ( 110 equality;1383 variable)
%            Maximal formula depth :   23 (   9 average)
%            Number of connectives : 2130 ( 102   ~;   0   |;  16   &;1773   @)
%                                         (  35 <=>; 204  =>;   0  <=;   0 <~>)
%                                         (   0  ~|;   0  ~&)
%            Number of type conns  :  320 ( 320   >;   0   *;   0   +;   0  <<)
%            Number of symbols     :   71 (  67   :;   0   =;   0  @=)
%                                         (   5  !!;   5  ??;   0 @@+;   0 @@-)
%            Number of variables   :  728 (   0 sgn; 715   !;  13   ?;   0   ^)
%                                         ( 728   :;   0  !>;   0  ?*)
%                                         (   0  @-;   0  @+)
% SPC      : TH1_THM_EQU_NAR

% Comments : This file was generated by Isabelle (most likely Sledgehammer)
%            2011-08-09 19:11:46
%------------------------------------------------------------------------------
%----Should-be-implicit typings (17)
thf(ty_ty_tc__Expr__Oexp_Itc__List__Olist_Itc__String__Ochar_J_J,type,(
    exp_list_char: $tType )).

thf(ty_ty_tc__List__Olist_Itc__String__Ochar_J,type,(
    list_char: $tType )).

thf(ty_ty_tc__List__Olist_Itc__prod_Itc__List__Olist_Itc__String__Ochar_J_Mtc__prod_,type,(
    list_P1999446415t_char: $tType )).

thf(ty_ty_tc__Nat__Onat,type,(
    nat: $tType )).

thf(ty_ty_tc__Option__Ooption_Itc__Type__Oty_J,type,(
    option_ty: $tType )).

thf(ty_ty_tc__Option__Ooption_Itc__Value__Oval_J,type,(
    option_val: $tType )).

thf(ty_ty_tc__Option__Ooption_Itc__prod_Itc__List__Olist_Itc__String__Ochar_J_M_062_,type,(
    option1728594148on_val: $tType )).

thf(ty_ty_tc__Type__Oty,type,(
    ty: $tType )).

thf(ty_ty_tc__Value__Oval,type,(
    val: $tType )).

thf(ty_ty_tc__prod_I_062_Itc__Nat__Onat_Mtc__Option__Ooption_Itc__prod_Itc__List__Ol,type,(
    produc2090907612on_val: $tType )).

thf(ty_ty_tc__prod_Itc__Expr__Oexp_Itc__List__Olist_Itc__String__Ochar_J_J_Mtc__prod,type,(
    produc1282892786on_val: $tType )).

thf(ty_ty_tc__prod_Itc__List__Olist_Itc__String__Ochar_J_Mtc__prod_Itc__List__Olist_,type,(
    produc1013743697t_char: $tType )).

thf(ty_ty_tc__prod_Itc__prod_I_062_Itc__Nat__Onat_Mtc__Option__Ooption_Itc__prod_Itc,type,(
    produc1581780743on_val: $tType )).

thf(ty_ty_tc__prod_Itc__prod_Itc__Expr__Oexp_Itc__List__Olist_Itc__String__Ochar_J_J,type,(
    produc1746408499on_val: $tType )).

thf(ty_ty_tc__prod_Itc__prod_Itc__prod_I_062_Itc__Nat__Onat_Mtc__Option__Ooption_Itc,type,(
    produc93741661on_val: $tType )).

thf(ty_ty_tc__prod_Itc__prod_Itc__prod_Itc__Expr__Oexp_Itc__List__Olist_Itc__String_,type,(
    produc652964533on_val: $tType )).

thf(ty_ty_tc__prod_Itc__prod_Itc__prod_Itc__prod_Itc__Expr__Oexp_Itc__List__Olist_It,type,(
    produc1206428857on_val: $tType )).

%----Explicit typings (60)
thf(sy_c_Conform_Ohconf_000tc__prod_Itc__List__Olist_Itc__List__Olist_Itc__String__O,type,(
    hconf_97414254t_char: list_P1999446415t_char > ( nat > option1728594148on_val ) > $o )).

thf(sy_c_Conform_Olconf_000tc__prod_Itc__List__Olist_Itc__List__Olist_Itc__String__O,type,(
    lconf_496643946t_char: list_P1999446415t_char > ( nat > option1728594148on_val ) > ( list_char > option_val ) > ( list_char > option_ty ) > $o )).

thf(sy_c_Expr_Oexp_OFAcc_000tc__List__Olist_Itc__String__Ochar_J,type,(
    fAcc_list_char: exp_list_char > list_char > list_char > exp_list_char )).

thf(sy_c_Expr_Oexp_OFAss_000tc__List__Olist_Itc__String__Ochar_J,type,(
    fAss_list_char: exp_list_char > list_char > list_char > exp_list_char > exp_list_char )).

thf(sy_c_Expr_Oexp_OTryCatch_000tc__List__Olist_Itc__String__Ochar_J,type,(
    tryCatch_list_char: exp_list_char > list_char > list_char > exp_list_char > exp_list_char )).

thf(sy_c_Expr_Oexp_OVal_000tc__List__Olist_Itc__String__Ochar_J,type,(
    val_list_char: val > exp_list_char )).

thf(sy_c_Expr_Oexp_Othrow_000tc__List__Olist_Itc__String__Ochar_J,type,(
    throw_list_char: exp_list_char > exp_list_char )).

thf(sy_c_JWellForm_Owf__J__mdecl,type,(
    wf_J_mdecl: list_P1999446415t_char > list_char > produc1013743697t_char > $o )).

thf(sy_c_Map_Omap__add_000tc__List__Olist_Itc__String__Ochar_J_000tc__Value__Oval,type,(
    map_ad325961431ar_val: ( list_char > option_val ) > ( list_char > option_val ) > list_char > option_val )).

thf(sy_c_Objects_Ohext,type,(
    hext: ( nat > option1728594148on_val ) > ( nat > option1728594148on_val ) > $o )).

thf(sy_c_Product__Type_OPair_000_062_Itc__Nat__Onat_Mtc__Option__Ooption_Itc__prod_I,type,(
    produc755559506on_val: ( nat > option1728594148on_val ) > ( list_char > option_val ) > produc2090907612on_val )).

thf(sy_c_Product__Type_OPair_000tc__Expr__Oexp_Itc__List__Olist_Itc__String__Ochar_J,type,(
    produc235638504on_val: exp_list_char > produc2090907612on_val > produc1282892786on_val )).

thf(sy_c_Product__Type_OPair_000tc__prod_I_062_Itc__Nat__Onat_Mtc__Option__Ooption_I,type,(
    produc259392253on_val: produc2090907612on_val > produc2090907612on_val > produc1581780743on_val )).

thf(sy_c_Product__Type_OPair_000tc__prod_Itc__Expr__Oexp_Itc__List__Olist_Itc__Strin,type,(
    produc833389609on_val: produc1282892786on_val > produc1282892786on_val > produc1746408499on_val )).

thf(sy_c_Product__Type_OPair_000tc__prod_Itc__prod_I_062_Itc__Nat__Onat_Mtc__Option_,type,(
    produc60772691on_val: produc1581780743on_val > produc1581780743on_val > produc93741661on_val )).

thf(sy_c_Product__Type_OPair_000tc__prod_Itc__prod_Itc__Expr__Oexp_Itc__List__Olist_,type,(
    produc345758123on_val: produc1746408499on_val > produc1746408499on_val > produc652964533on_val )).

thf(sy_c_Product__Type_OPair_000tc__prod_Itc__prod_Itc__prod_Itc__Expr__Oexp_Itc__Li,type,(
    produc900610479on_val: produc652964533on_val > produc652964533on_val > produc1206428857on_val )).

thf(sy_c_SmallStep_Ored,type,(
    red: list_P1999446415t_char > produc1746408499on_val > $o )).

thf(sy_c_State_Ohp,type,(
    hp: produc2090907612on_val > nat > option1728594148on_val )).

thf(sy_c_Transitive__Closure_Ortrancl_000tc__prod_I_062_Itc__Nat__Onat_Mtc__Option__,type,(
    transi466770671on_val: ( produc1581780743on_val > $o ) > produc1581780743on_val > $o )).

thf(sy_c_Transitive__Closure_Ortrancl_000tc__prod_Itc__Expr__Oexp_Itc__List__Olist_I,type,(
    transi2118771717on_val: ( produc1746408499on_val > $o ) > produc1746408499on_val > $o )).

thf(sy_c_Transitive__Closure_Ortrancl_000tc__prod_Itc__prod_I_062_Itc__Nat__Onat_Mtc,type,(
    transi289221018on_val: ( produc93741661on_val > $o ) > produc93741661on_val > $o )).

thf(sy_c_Transitive__Closure_Ortrancl_000tc__prod_Itc__prod_Itc__Expr__Oexp_Itc__Lis,type,(
    transi130214086on_val: ( produc652964533on_val > $o ) > produc652964533on_val > $o )).

thf(sy_c_Transitive__Closure_Ortrancl_000tc__prod_Itc__prod_Itc__prod_Itc__Expr__Oex,type,(
    transi1461661768on_val: ( produc1206428857on_val > $o ) > produc1206428857on_val > $o )).

thf(sy_c_TypeRel_Owiden_000tc__prod_Itc__List__Olist_Itc__List__Olist_Itc__String__O,type,(
    widen_2090681816t_char: list_P1999446415t_char > ty > ty > $o )).

thf(sy_c_TypeSafe__Mirabelle__nzycqussuh_Osconf,type,(
    typeSa1586500134_sconf: list_P1999446415t_char > ( list_char > option_ty ) > produc2090907612on_val > $o )).

thf(sy_c_Type_Oty_OBoolean,type,(
    boolean: ty )).

thf(sy_c_Type_Oty_ONT,type,(
    nt: ty )).

thf(sy_c_Type_Oty_OVoid,type,(
    void: ty )).

thf(sy_c_WellForm_Owf__prog_000tc__prod_Itc__List__Olist_Itc__List__Olist_Itc__Strin,type,(
    wf_pro755087577t_char: ( list_P1999446415t_char > list_char > produc1013743697t_char > $o ) > list_P1999446415t_char > $o )).

thf(sy_c_WellTypeRT_OWTrt,type,(
    wTrt: list_P1999446415t_char > ( nat > option1728594148on_val ) > ( list_char > option_ty ) > exp_list_char > ty > $o )).

thf(sy_c_member_000tc__prod_I_062_Itc__Nat__Onat_Mtc__Option__Ooption_Itc__prod_Itc_,type,(
    member1846553161on_val: produc2090907612on_val > ( produc2090907612on_val > $o ) > $o )).

thf(sy_c_member_000tc__prod_Itc__Expr__Oexp_Itc__List__Olist_Itc__String__Ochar_J_J_,type,(
    member1072200031on_val: produc1282892786on_val > ( produc1282892786on_val > $o ) > $o )).

thf(sy_c_member_000tc__prod_Itc__prod_I_062_Itc__Nat__Onat_Mtc__Option__Ooption_Itc_,type,(
    member565037556on_val: produc1581780743on_val > ( produc1581780743on_val > $o ) > $o )).

thf(sy_c_member_000tc__prod_Itc__prod_Itc__Expr__Oexp_Itc__List__Olist_Itc__String__,type,(
    member1913460000on_val: produc1746408499on_val > ( produc1746408499on_val > $o ) > $o )).

thf(sy_c_member_000tc__prod_Itc__prod_Itc__prod_I_062_Itc__Nat__Onat_Mtc__Option__Oo,type,(
    member1519152714on_val: produc93741661on_val > ( produc93741661on_val > $o ) > $o )).

thf(sy_c_member_000tc__prod_Itc__prod_Itc__prod_Itc__Expr__Oexp_Itc__List__Olist_Itc,type,(
    member1714424482on_val: produc652964533on_val > ( produc652964533on_val > $o ) > $o )).

thf(sy_c_member_000tc__prod_Itc__prod_Itc__prod_Itc__prod_Itc__Expr__Oexp_Itc__List_,type,(
    member1735092902on_val: produc1206428857on_val > ( produc1206428857on_val > $o ) > $o )).

thf(sy_v_D____,type,(
    d: list_char )).

thf(sy_v_E____,type,(
    e: list_char > option_ty )).

thf(sy_v_F____,type,(
    f: list_char )).

thf(sy_v_P,type,(
    p: list_P1999446415t_char )).

thf(sy_v_T____,type,(
    t: ty )).

thf(sy_v_e_092_060_094isub_0622____,type,(
    e_2: exp_list_char )).

thf(sy_v_e_Ha____,type,(
    e_a: exp_list_char )).

thf(sy_v_ea____,type,(
    ea: exp_list_char )).

thf(sy_v_h_Ha____,type,(
    h_a: nat > option1728594148on_val )).

thf(sy_v_ha____,type,(
    ha: nat > option1728594148on_val )).

thf(sy_v_l_Ha____,type,(
    l_a: list_char > option_val )).

thf(sy_v_la____,type,(
    la: list_char > option_val )).

%----Relevant facts (162)
thf(fact_0__096P_ME_Mh_A_092_060turnstile_062_Ae_A_058_ANT_096,axiom,
    ( wTrt @ p @ ha @ e @ ea @ nt )).

thf(fact_1__096_B_BT_O_AP_ME_Mh_A_092_060turnstile_062_Ae_A_058_AT_A_061_061_062_AEX,axiom,(
    ! [T: ty] :
      ( ( wTrt @ p @ ha @ e @ ea @ T )
     => ? [U_1: ty] :
          ( ( wTrt @ p @ h_a @ e @ e_a @ U_1 )
          & ( widen_2090681816t_char @ p @ U_1 @ T ) ) ) )).

thf(fact_2_assms,axiom,
    ( wf_pro755087577t_char @ wf_J_mdecl @ p )).

thf(fact_3_IH,axiom,(
    ! [T: ty,E_5: list_char > option_ty] :
      ( ( typeSa1586500134_sconf @ p @ E_5 @ ( produc755559506on_val @ ha @ la ) )
     => ( ( wTrt @ p @ ha @ E_5 @ ea @ T )
       => ? [U_1: ty] :
            ( ( wTrt @ p @ h_a @ E_5 @ e_a @ U_1 )
            & ( widen_2090681816t_char @ p @ U_1 @ T ) ) ) ) )).

thf(fact_4_conf,axiom,
    ( typeSa1586500134_sconf @ p @ e @ ( produc755559506on_val @ ha @ la ) )).

thf(fact_5_wt,axiom,
    ( wTrt @ p @ ha @ e @ ( fAss_list_char @ ea @ f @ d @ e_2 ) @ t )).

thf(fact_6_WTrtFAccNT,axiom,(
    ! [F: list_char,D: list_char,T: ty,P: list_P1999446415t_char,H_1: nat > option1728594148on_val,E_5: list_char > option_ty,E: exp_list_char] :
      ( ( wTrt @ P @ H_1 @ E_5 @ E @ nt )
     => ( wTrt @ P @ H_1 @ E_5 @ ( fAcc_list_char @ E @ F @ D ) @ T ) ) )).

thf(fact_7_FAssRed1_I2_J,axiom,(
    ! [T: ty,E_5: list_char > option_ty] :
      ( ( typeSa1586500134_sconf @ p @ E_5 @ ( produc755559506on_val @ ha @ la ) )
     => ( ( wTrt @ p @ ha @ E_5 @ ea @ T )
       => ? [T_4: ty] :
            ( ( wTrt @ p @ h_a @ E_5 @ e_a @ T_4 )
            & ( widen_2090681816t_char @ p @ T_4 @ T ) ) ) ) )).

thf(fact_8_red,axiom,
    ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ ea @ ( produc755559506on_val @ ha @ la ) ) @ ( produc235638504on_val @ e_a @ ( produc755559506on_val @ h_a @ l_a ) ) ) @ ( red @ p ) )).

thf(fact_9_FAssRed1_I4_J,axiom,
    ( wTrt @ p @ ha @ e @ ( fAss_list_char @ ea @ f @ d @ e_2 ) @ t )).

thf(fact_10_FAssRed1_I3_J,axiom,
    ( typeSa1586500134_sconf @ p @ e @ ( produc755559506on_val @ ha @ la ) )).

thf(fact_11_ty_Osimps_I13_J,axiom,(
    nt != boolean )).

thf(fact_12_ty_Osimps_I12_J,axiom,(
    boolean != nt )).

thf(fact_13_red__reds_OFAccRed,axiom,(
    ! [F: list_char,D: list_char,E: exp_list_char,S_1: produc2090907612on_val,E_3: exp_list_char,S: produc2090907612on_val,P: list_P1999446415t_char] :
      ( ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ E @ S_1 ) @ ( produc235638504on_val @ E_3 @ S ) ) @ ( red @ P ) )
     => ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ ( fAcc_list_char @ E @ F @ D ) @ S_1 ) @ ( produc235638504on_val @ ( fAcc_list_char @ E_3 @ F @ D ) @ S ) ) @ ( red @ P ) ) ) )).

thf(fact_14_red__reds_OFAssRed1,axiom,(
    ! [F: list_char,D: list_char,E_2: exp_list_char,E: exp_list_char,S_1: produc2090907612on_val,E_3: exp_list_char,S: produc2090907612on_val,P: list_P1999446415t_char] :
      ( ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ E @ S_1 ) @ ( produc235638504on_val @ E_3 @ S ) ) @ ( red @ P ) )
     => ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ ( fAss_list_char @ E @ F @ D @ E_2 ) @ S_1 ) @ ( produc235638504on_val @ ( fAss_list_char @ E_3 @ F @ D @ E_2 ) @ S ) ) @ ( red @ P ) ) ) )).

thf(fact_15_void,axiom,(
    t = void )).

thf(fact_16_widen__refl,axiom,(
    ! [P_14: list_P1999446415t_char,T_3: ty] :
      ( widen_2090681816t_char @ P_14 @ T_3 @ T_3 ) )).

thf(fact_17_red__preserves__hconf,axiom,(
    ! [E_5: list_char > option_ty,T: ty,E: exp_list_char,H_1: nat > option1728594148on_val,L_1: list_char > option_val,E_3: exp_list_char,H: nat > option1728594148on_val,L: list_char > option_val,P: list_P1999446415t_char] :
      ( ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ E @ ( produc755559506on_val @ H_1 @ L_1 ) ) @ ( produc235638504on_val @ E_3 @ ( produc755559506on_val @ H @ L ) ) ) @ ( red @ P ) )
     => ( ( wTrt @ P @ H_1 @ E_5 @ E @ T )
       => ( ( hconf_97414254t_char @ P @ H_1 )
         => ( hconf_97414254t_char @ P @ H ) ) ) ) )).

thf(fact_18_red__preserves__lconf,axiom,(
    ! [E_5: list_char > option_ty,T: ty,E: exp_list_char,H_1: nat > option1728594148on_val,L_1: list_char > option_val,E_3: exp_list_char,H: nat > option1728594148on_val,L: list_char > option_val,P: list_P1999446415t_char] :
      ( ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ E @ ( produc755559506on_val @ H_1 @ L_1 ) ) @ ( produc235638504on_val @ E_3 @ ( produc755559506on_val @ H @ L ) ) ) @ ( red @ P ) )
     => ( ( wTrt @ P @ H_1 @ E_5 @ E @ T )
       => ( ( lconf_496643946t_char @ P @ H_1 @ L_1 @ E_5 )
         => ( lconf_496643946t_char @ P @ H @ L @ E_5 ) ) ) ) )).

thf(fact_19_exp_Osimps_I154_J,axiom,(
    ! [Exp_18: exp_list_char,List1_19: list_char,List2_19: list_char,Exp1_18: exp_list_char,List1_18: list_char,List2_18: list_char,Exp2_18: exp_list_char] :
      ( ( fAcc_list_char @ Exp_18 @ List1_19 @ List2_19 )
     != ( fAss_list_char @ Exp1_18 @ List1_18 @ List2_18 @ Exp2_18 ) ) )).

thf(fact_20_exp_Osimps_I155_J,axiom,(
    ! [Exp1_17: exp_list_char,List1_17: list_char,List2_17: list_char,Exp2_17: exp_list_char,Exp_17: exp_list_char,List1_16: list_char,List2_16: list_char] :
      ( ( fAss_list_char @ Exp1_17 @ List1_17 @ List2_17 @ Exp2_17 )
     != ( fAcc_list_char @ Exp_17 @ List1_16 @ List2_16 ) ) )).

thf(fact_21_red__preserves__sconf,axiom,(
    ! [E_5: list_char > option_ty,T: ty,E: exp_list_char,S_1: produc2090907612on_val,E_3: exp_list_char,S: produc2090907612on_val,P: list_P1999446415t_char] :
      ( ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ E @ S_1 ) @ ( produc235638504on_val @ E_3 @ S ) ) @ ( red @ P ) )
     => ( ( wTrt @ P @ ( hp @ S_1 ) @ E_5 @ E @ T )
       => ( ( typeSa1586500134_sconf @ P @ E_5 @ S_1 )
         => ( typeSa1586500134_sconf @ P @ E_5 @ S ) ) ) ) )).

thf(fact_22_ty_Osimps_I7_J,axiom,(
    nt != void )).

thf(fact_23_ty_Osimps_I6_J,axiom,(
    void != nt )).

thf(fact_24_ty_Osimps_I3_J,axiom,(
    boolean != void )).

thf(fact_25_ty_Osimps_I2_J,axiom,(
    void != boolean )).

thf(fact_26_widen__trans,axiom,(
    ! [T_1: ty,P_13: list_P1999446415t_char,S_4: ty,U: ty] :
      ( ( widen_2090681816t_char @ P_13 @ S_4 @ U )
     => ( ( widen_2090681816t_char @ P_13 @ U @ T_1 )
       => ( widen_2090681816t_char @ P_13 @ S_4 @ T_1 ) ) ) )).

thf(fact_27_exp_Osimps_I8_J,axiom,(
    ! [Exp1_16: exp_list_char,List1_15: list_char,List2_15: list_char,Exp2_16: exp_list_char,Exp1_15: exp_list_char,List1_14: list_char,List2_14: list_char,Exp2_15: exp_list_char] :
      ( ( ( fAss_list_char @ Exp1_16 @ List1_15 @ List2_15 @ Exp2_16 )
        = ( fAss_list_char @ Exp1_15 @ List1_14 @ List2_14 @ Exp2_15 ) )
    <=> ( ( Exp1_16 = Exp1_15 )
        & ( List1_15 = List1_14 )
        & ( List2_15 = List2_14 )
        & ( Exp2_16 = Exp2_15 ) ) ) )).

thf(fact_28_exp_Osimps_I7_J,axiom,(
    ! [Exp_16: exp_list_char,List1_13: list_char,List2_13: list_char,Exp_15: exp_list_char,List1_12: list_char,List2_12: list_char] :
      ( ( ( fAcc_list_char @ Exp_16 @ List1_13 @ List2_13 )
        = ( fAcc_list_char @ Exp_15 @ List1_12 @ List2_12 ) )
    <=> ( ( Exp_16 = Exp_15 )
        & ( List1_13 = List1_12 )
        & ( List2_13 = List2_12 ) ) ) )).

thf(fact_29_WTrtFAssNT,axiom,(
    ! [F: list_char,D: list_char,E_2: exp_list_char,T_2: ty,P: list_P1999446415t_char,H_1: nat > option1728594148on_val,E_5: list_char > option_ty,E_1: exp_list_char] :
      ( ( wTrt @ P @ H_1 @ E_5 @ E_1 @ nt )
     => ( ( wTrt @ P @ H_1 @ E_5 @ E_2 @ T_2 )
       => ( wTrt @ P @ H_1 @ E_5 @ ( fAss_list_char @ E_1 @ F @ D @ E_2 ) @ void ) ) ) )).

thf(fact_30_red__hext__incr,axiom,(
    ! [E: exp_list_char,H_1: nat > option1728594148on_val,L_1: list_char > option_val,E_3: exp_list_char,H: nat > option1728594148on_val,L: list_char > option_val,P: list_P1999446415t_char] :
      ( ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ E @ ( produc755559506on_val @ H_1 @ L_1 ) ) @ ( produc235638504on_val @ E_3 @ ( produc755559506on_val @ H @ L ) ) ) @ ( red @ P ) )
     => ( hext @ H_1 @ H ) ) )).

thf(fact_31_prod__cases4,axiom,(
    ! [Y_4: produc1746408499on_val] :
      ~ ( ! [A_13: produc1282892786on_val,B_3: exp_list_char,C_4: nat > option1728594148on_val,D_1: list_char > option_val] :
            ( Y_4
           != ( produc833389609on_val @ A_13 @ ( produc235638504on_val @ B_3 @ ( produc755559506on_val @ C_4 @ D_1 ) ) ) ) ) )).

thf(fact_32_prod__cases4,axiom,(
    ! [Y_4: produc652964533on_val] :
      ~ ( ! [A_13: produc1746408499on_val,B_3: produc1282892786on_val,C_4: exp_list_char,D_1: produc2090907612on_val] :
            ( Y_4
           != ( produc345758123on_val @ A_13 @ ( produc833389609on_val @ B_3 @ ( produc235638504on_val @ C_4 @ D_1 ) ) ) ) ) )).

thf(fact_33_prod__induct4,axiom,(
    ! [X_5: produc1746408499on_val,P_12: produc1746408499on_val > $o] :
      ( ! [A_13: produc1282892786on_val,B_3: exp_list_char,C_4: nat > option1728594148on_val,D_1: list_char > option_val] :
          ( P_12 @ ( produc833389609on_val @ A_13 @ ( produc235638504on_val @ B_3 @ ( produc755559506on_val @ C_4 @ D_1 ) ) ) )
     => ( P_12 @ X_5 ) ) )).

thf(fact_34_prod__induct4,axiom,(
    ! [X_5: produc652964533on_val,P_12: produc652964533on_val > $o] :
      ( ! [A_13: produc1746408499on_val,B_3: produc1282892786on_val,C_4: exp_list_char,D_1: produc2090907612on_val] :
          ( P_12 @ ( produc345758123on_val @ A_13 @ ( produc833389609on_val @ B_3 @ ( produc235638504on_val @ C_4 @ D_1 ) ) ) )
     => ( P_12 @ X_5 ) ) )).

thf(fact_35_prod__cases5,axiom,(
    ! [Y_3: produc652964533on_val] :
      ~ ( ! [A_13: produc1746408499on_val,B_3: produc1282892786on_val,C_4: exp_list_char,D_1: nat > option1728594148on_val,E_6: list_char > option_val] :
            ( Y_3
           != ( produc345758123on_val @ A_13 @ ( produc833389609on_val @ B_3 @ ( produc235638504on_val @ C_4 @ ( produc755559506on_val @ D_1 @ E_6 ) ) ) ) ) ) )).

thf(fact_36_prod__induct5,axiom,(
    ! [X_4: produc652964533on_val,P_11: produc652964533on_val > $o] :
      ( ! [A_13: produc1746408499on_val,B_3: produc1282892786on_val,C_4: exp_list_char,D_1: nat > option1728594148on_val,E_6: list_char > option_val] :
          ( P_11 @ ( produc345758123on_val @ A_13 @ ( produc833389609on_val @ B_3 @ ( produc235638504on_val @ C_4 @ ( produc755559506on_val @ D_1 @ E_6 ) ) ) ) )
     => ( P_11 @ X_4 ) ) )).

thf(fact_37_WTrt__hext__mono,axiom,(
    ! [H: nat > option1728594148on_val,P: list_P1999446415t_char,H_1: nat > option1728594148on_val,E_5: list_char > option_ty,E: exp_list_char,T: ty] :
      ( ( wTrt @ P @ H_1 @ E_5 @ E @ T )
     => ( ( hext @ H_1 @ H )
       => ( wTrt @ P @ H @ E_5 @ E @ T ) ) ) )).

thf(fact_38_split__paired__All,axiom,(
    ! [P_10: produc652964533on_val > $o] :
      ( ( !! @ produc652964533on_val @ P_10 )
    <=> ! [A_13: produc1746408499on_val,B_3: produc1746408499on_val] :
          ( P_10 @ ( produc345758123on_val @ A_13 @ B_3 ) ) ) )).

thf(fact_39_split__paired__All,axiom,(
    ! [P_10: produc1581780743on_val > $o] :
      ( ( !! @ produc1581780743on_val @ P_10 )
    <=> ! [A_13: produc2090907612on_val,B_3: produc2090907612on_val] :
          ( P_10 @ ( produc259392253on_val @ A_13 @ B_3 ) ) ) )).

thf(fact_40_split__paired__All,axiom,(
    ! [P_10: produc2090907612on_val > $o] :
      ( ( !! @ produc2090907612on_val @ P_10 )
    <=> ! [A_13: nat > option1728594148on_val,B_3: list_char > option_val] :
          ( P_10 @ ( produc755559506on_val @ A_13 @ B_3 ) ) ) )).

thf(fact_41_split__paired__All,axiom,(
    ! [P_10: produc1746408499on_val > $o] :
      ( ( !! @ produc1746408499on_val @ P_10 )
    <=> ! [A_13: produc1282892786on_val,B_3: produc1282892786on_val] :
          ( P_10 @ ( produc833389609on_val @ A_13 @ B_3 ) ) ) )).

thf(fact_42_split__paired__All,axiom,(
    ! [P_10: produc1282892786on_val > $o] :
      ( ( !! @ produc1282892786on_val @ P_10 )
    <=> ! [A_13: exp_list_char,B_3: produc2090907612on_val] :
          ( P_10 @ ( produc235638504on_val @ A_13 @ B_3 ) ) ) )).

thf(fact_43_Pair__eq,axiom,(
    ! [A_21: produc1746408499on_val,B_10: produc1746408499on_val,A_20: produc1746408499on_val,B_9: produc1746408499on_val] :
      ( ( ( produc345758123on_val @ A_21 @ B_10 )
        = ( produc345758123on_val @ A_20 @ B_9 ) )
    <=> ( ( A_21 = A_20 )
        & ( B_10 = B_9 ) ) ) )).

thf(fact_44_Pair__eq,axiom,(
    ! [A_21: produc2090907612on_val,B_10: produc2090907612on_val,A_20: produc2090907612on_val,B_9: produc2090907612on_val] :
      ( ( ( produc259392253on_val @ A_21 @ B_10 )
        = ( produc259392253on_val @ A_20 @ B_9 ) )
    <=> ( ( A_21 = A_20 )
        & ( B_10 = B_9 ) ) ) )).

thf(fact_45_Pair__eq,axiom,(
    ! [A_21: nat > option1728594148on_val,B_10: list_char > option_val,A_20: nat > option1728594148on_val,B_9: list_char > option_val] :
      ( ( ( produc755559506on_val @ A_21 @ B_10 )
        = ( produc755559506on_val @ A_20 @ B_9 ) )
    <=> ( ( A_21 = A_20 )
        & ( B_10 = B_9 ) ) ) )).

thf(fact_46_Pair__eq,axiom,(
    ! [A_21: produc1282892786on_val,B_10: produc1282892786on_val,A_20: produc1282892786on_val,B_9: produc1282892786on_val] :
      ( ( ( produc833389609on_val @ A_21 @ B_10 )
        = ( produc833389609on_val @ A_20 @ B_9 ) )
    <=> ( ( A_21 = A_20 )
        & ( B_10 = B_9 ) ) ) )).

thf(fact_47_Pair__eq,axiom,(
    ! [A_21: exp_list_char,B_10: produc2090907612on_val,A_20: exp_list_char,B_9: produc2090907612on_val] :
      ( ( ( produc235638504on_val @ A_21 @ B_10 )
        = ( produc235638504on_val @ A_20 @ B_9 ) )
    <=> ( ( A_21 = A_20 )
        & ( B_10 = B_9 ) ) ) )).

thf(fact_48_Pair__inject,axiom,(
    ! [A_19: produc1746408499on_val,B_8: produc1746408499on_val,A_18: produc1746408499on_val,B_7: produc1746408499on_val] :
      ( ( ( produc345758123on_val @ A_19 @ B_8 )
        = ( produc345758123on_val @ A_18 @ B_7 ) )
     => ~ ( ( A_19 = A_18 )
         => ( B_8 != B_7 ) ) ) )).

thf(fact_49_Pair__inject,axiom,(
    ! [A_19: produc2090907612on_val,B_8: produc2090907612on_val,A_18: produc2090907612on_val,B_7: produc2090907612on_val] :
      ( ( ( produc259392253on_val @ A_19 @ B_8 )
        = ( produc259392253on_val @ A_18 @ B_7 ) )
     => ~ ( ( A_19 = A_18 )
         => ( B_8 != B_7 ) ) ) )).

thf(fact_50_Pair__inject,axiom,(
    ! [A_19: nat > option1728594148on_val,B_8: list_char > option_val,A_18: nat > option1728594148on_val,B_7: list_char > option_val] :
      ( ( ( produc755559506on_val @ A_19 @ B_8 )
        = ( produc755559506on_val @ A_18 @ B_7 ) )
     => ~ ( ( A_19 = A_18 )
         => ( B_8 != B_7 ) ) ) )).

thf(fact_51_Pair__inject,axiom,(
    ! [A_19: produc1282892786on_val,B_8: produc1282892786on_val,A_18: produc1282892786on_val,B_7: produc1282892786on_val] :
      ( ( ( produc833389609on_val @ A_19 @ B_8 )
        = ( produc833389609on_val @ A_18 @ B_7 ) )
     => ~ ( ( A_19 = A_18 )
         => ( B_8 != B_7 ) ) ) )).

thf(fact_52_Pair__inject,axiom,(
    ! [A_19: exp_list_char,B_8: produc2090907612on_val,A_18: exp_list_char,B_7: produc2090907612on_val] :
      ( ( ( produc235638504on_val @ A_19 @ B_8 )
        = ( produc235638504on_val @ A_18 @ B_7 ) )
     => ~ ( ( A_19 = A_18 )
         => ( B_8 != B_7 ) ) ) )).

thf(fact_53_hext__refl,axiom,(
    ! [H_1: nat > option1728594148on_val] :
      ( hext @ H_1 @ H_1 ) )).

thf(fact_54_lconf__hext,axiom,(
    ! [H_4: nat > option1728594148on_val,P_9: list_P1999446415t_char,H_3: nat > option1728594148on_val,L_2: list_char > option_val,E_4: list_char > option_ty] :
      ( ( lconf_496643946t_char @ P_9 @ H_3 @ L_2 @ E_4 )
     => ( ( hext @ H_3 @ H_4 )
       => ( lconf_496643946t_char @ P_9 @ H_4 @ L_2 @ E_4 ) ) ) )).

thf(fact_55_prod__induct3,axiom,(
    ! [X_3: produc1746408499on_val,P_8: produc1746408499on_val > $o] :
      ( ! [A_13: produc1282892786on_val,B_3: exp_list_char,C_4: produc2090907612on_val] :
          ( P_8 @ ( produc833389609on_val @ A_13 @ ( produc235638504on_val @ B_3 @ C_4 ) ) )
     => ( P_8 @ X_3 ) ) )).

thf(fact_56_prod__induct3,axiom,(
    ! [X_3: produc1282892786on_val,P_8: produc1282892786on_val > $o] :
      ( ! [A_13: exp_list_char,B_3: nat > option1728594148on_val,C_4: list_char > option_val] :
          ( P_8 @ ( produc235638504on_val @ A_13 @ ( produc755559506on_val @ B_3 @ C_4 ) ) )
     => ( P_8 @ X_3 ) ) )).

thf(fact_57_prod__induct3,axiom,(
    ! [X_3: produc1581780743on_val,P_8: produc1581780743on_val > $o] :
      ( ! [A_13: produc2090907612on_val,B_3: nat > option1728594148on_val,C_4: list_char > option_val] :
          ( P_8 @ ( produc259392253on_val @ A_13 @ ( produc755559506on_val @ B_3 @ C_4 ) ) )
     => ( P_8 @ X_3 ) ) )).

thf(fact_58_prod__induct3,axiom,(
    ! [X_3: produc652964533on_val,P_8: produc652964533on_val > $o] :
      ( ! [A_13: produc1746408499on_val,B_3: produc1282892786on_val,C_4: produc1282892786on_val] :
          ( P_8 @ ( produc345758123on_val @ A_13 @ ( produc833389609on_val @ B_3 @ C_4 ) ) )
     => ( P_8 @ X_3 ) ) )).

thf(fact_59_prod__cases3,axiom,(
    ! [Y_2: produc1746408499on_val] :
      ~ ( ! [A_13: produc1282892786on_val,B_3: exp_list_char,C_4: produc2090907612on_val] :
            ( Y_2
           != ( produc833389609on_val @ A_13 @ ( produc235638504on_val @ B_3 @ C_4 ) ) ) ) )).

thf(fact_60_prod__cases3,axiom,(
    ! [Y_2: produc1282892786on_val] :
      ~ ( ! [A_13: exp_list_char,B_3: nat > option1728594148on_val,C_4: list_char > option_val] :
            ( Y_2
           != ( produc235638504on_val @ A_13 @ ( produc755559506on_val @ B_3 @ C_4 ) ) ) ) )).

thf(fact_61_prod__cases3,axiom,(
    ! [Y_2: produc1581780743on_val] :
      ~ ( ! [A_13: produc2090907612on_val,B_3: nat > option1728594148on_val,C_4: list_char > option_val] :
            ( Y_2
           != ( produc259392253on_val @ A_13 @ ( produc755559506on_val @ B_3 @ C_4 ) ) ) ) )).

thf(fact_62_prod__cases3,axiom,(
    ! [Y_2: produc652964533on_val] :
      ~ ( ! [A_13: produc1746408499on_val,B_3: produc1282892786on_val,C_4: produc1282892786on_val] :
            ( Y_2
           != ( produc345758123on_val @ A_13 @ ( produc833389609on_val @ B_3 @ C_4 ) ) ) ) )).

thf(fact_63_hext__trans,axiom,(
    ! [H_2: nat > option1728594148on_val,H_1: nat > option1728594148on_val,H: nat > option1728594148on_val] :
      ( ( hext @ H_1 @ H )
     => ( ( hext @ H @ H_2 )
       => ( hext @ H_1 @ H_2 ) ) ) )).

thf(fact_64_red__lcl__add,axiom,(
    ! [L_0: list_char > option_val,E: exp_list_char,H_1: nat > option1728594148on_val,L_1: list_char > option_val,E_3: exp_list_char,H: nat > option1728594148on_val,L: list_char > option_val,P: list_P1999446415t_char] :
      ( ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ E @ ( produc755559506on_val @ H_1 @ L_1 ) ) @ ( produc235638504on_val @ E_3 @ ( produc755559506on_val @ H @ L ) ) ) @ ( red @ P ) )
     => ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ E @ ( produc755559506on_val @ H_1 @ ( map_ad325961431ar_val @ L_0 @ L_1 ) ) ) @ ( produc235638504on_val @ E_3 @ ( produc755559506on_val @ H @ ( map_ad325961431ar_val @ L_0 @ L ) ) ) ) @ ( red @ P ) ) ) )).

thf(fact_65_pred__equals__eq2,axiom,(
    ! [S_3: produc652964533on_val > $o,R_13: produc652964533on_val > $o] :
      ( ! [X_2: produc1746408499on_val,Xa_1: produc1746408499on_val] :
          ( ( member1714424482on_val @ ( produc345758123on_val @ X_2 @ Xa_1 ) @ R_13 )
        <=> ( member1714424482on_val @ ( produc345758123on_val @ X_2 @ Xa_1 ) @ S_3 ) )
    <=> ( R_13 = S_3 ) ) )).

thf(fact_66_pred__equals__eq2,axiom,(
    ! [S_3: produc1581780743on_val > $o,R_13: produc1581780743on_val > $o] :
      ( ! [X_2: produc2090907612on_val,Xa_1: produc2090907612on_val] :
          ( ( member565037556on_val @ ( produc259392253on_val @ X_2 @ Xa_1 ) @ R_13 )
        <=> ( member565037556on_val @ ( produc259392253on_val @ X_2 @ Xa_1 ) @ S_3 ) )
    <=> ( R_13 = S_3 ) ) )).

thf(fact_67_pred__equals__eq2,axiom,(
    ! [S_3: produc2090907612on_val > $o,R_13: produc2090907612on_val > $o] :
      ( ! [X_2: nat > option1728594148on_val,Xa_1: list_char > option_val] :
          ( ( member1846553161on_val @ ( produc755559506on_val @ X_2 @ Xa_1 ) @ R_13 )
        <=> ( member1846553161on_val @ ( produc755559506on_val @ X_2 @ Xa_1 ) @ S_3 ) )
    <=> ( R_13 = S_3 ) ) )).

thf(fact_68_pred__equals__eq2,axiom,(
    ! [S_3: produc1282892786on_val > $o,R_13: produc1282892786on_val > $o] :
      ( ! [X_2: exp_list_char,Xa_1: produc2090907612on_val] :
          ( ( member1072200031on_val @ ( produc235638504on_val @ X_2 @ Xa_1 ) @ R_13 )
        <=> ( member1072200031on_val @ ( produc235638504on_val @ X_2 @ Xa_1 ) @ S_3 ) )
    <=> ( R_13 = S_3 ) ) )).

thf(fact_69_pred__equals__eq2,axiom,(
    ! [S_3: produc1746408499on_val > $o,R_13: produc1746408499on_val > $o] :
      ( ! [X_2: produc1282892786on_val,Xa_1: produc1282892786on_val] :
          ( ( member1913460000on_val @ ( produc833389609on_val @ X_2 @ Xa_1 ) @ R_13 )
        <=> ( member1913460000on_val @ ( produc833389609on_val @ X_2 @ Xa_1 ) @ S_3 ) )
    <=> ( R_13 = S_3 ) ) )).

thf(fact_70_prod_Oexhaust,axiom,(
    ! [Y_1: produc652964533on_val] :
      ~ ( ! [A_13: produc1746408499on_val,B_3: produc1746408499on_val] :
            ( Y_1
           != ( produc345758123on_val @ A_13 @ B_3 ) ) ) )).

thf(fact_71_prod_Oexhaust,axiom,(
    ! [Y_1: produc1581780743on_val] :
      ~ ( ! [A_13: produc2090907612on_val,B_3: produc2090907612on_val] :
            ( Y_1
           != ( produc259392253on_val @ A_13 @ B_3 ) ) ) )).

thf(fact_72_prod_Oexhaust,axiom,(
    ! [Y_1: produc2090907612on_val] :
      ~ ( ! [A_13: nat > option1728594148on_val,B_3: list_char > option_val] :
            ( Y_1
           != ( produc755559506on_val @ A_13 @ B_3 ) ) ) )).

thf(fact_73_prod_Oexhaust,axiom,(
    ! [Y_1: produc1746408499on_val] :
      ~ ( ! [A_13: produc1282892786on_val,B_3: produc1282892786on_val] :
            ( Y_1
           != ( produc833389609on_val @ A_13 @ B_3 ) ) ) )).

thf(fact_74_prod_Oexhaust,axiom,(
    ! [Y_1: produc1282892786on_val] :
      ~ ( ! [A_13: exp_list_char,B_3: produc2090907612on_val] :
            ( Y_1
           != ( produc235638504on_val @ A_13 @ B_3 ) ) ) )).

thf(fact_75_PairE,axiom,(
    ! [P_7: produc652964533on_val] :
      ~ ( ! [X_2: produc1746408499on_val,Y: produc1746408499on_val] :
            ( P_7
           != ( produc345758123on_val @ X_2 @ Y ) ) ) )).

thf(fact_76_PairE,axiom,(
    ! [P_7: produc1581780743on_val] :
      ~ ( ! [X_2: produc2090907612on_val,Y: produc2090907612on_val] :
            ( P_7
           != ( produc259392253on_val @ X_2 @ Y ) ) ) )).

thf(fact_77_PairE,axiom,(
    ! [P_7: produc2090907612on_val] :
      ~ ( ! [X_2: nat > option1728594148on_val,Y: list_char > option_val] :
            ( P_7
           != ( produc755559506on_val @ X_2 @ Y ) ) ) )).

thf(fact_78_PairE,axiom,(
    ! [P_7: produc1746408499on_val] :
      ~ ( ! [X_2: produc1282892786on_val,Y: produc1282892786on_val] :
            ( P_7
           != ( produc833389609on_val @ X_2 @ Y ) ) ) )).

thf(fact_79_PairE,axiom,(
    ! [P_7: produc1282892786on_val] :
      ~ ( ! [X_2: exp_list_char,Y: produc2090907612on_val] :
            ( P_7
           != ( produc235638504on_val @ X_2 @ Y ) ) ) )).

thf(fact_80_Red__lcl__add,axiom,(
    ! [L_0: list_char > option_val,E: exp_list_char,H_1: nat > option1728594148on_val,L_1: list_char > option_val,E_3: exp_list_char,H: nat > option1728594148on_val,L: list_char > option_val,P: list_P1999446415t_char] :
      ( ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ E @ ( produc755559506on_val @ H_1 @ L_1 ) ) @ ( produc235638504on_val @ E_3 @ ( produc755559506on_val @ H @ L ) ) ) @ ( transi2118771717on_val @ ( red @ P ) ) )
     => ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ E @ ( produc755559506on_val @ H_1 @ ( map_ad325961431ar_val @ L_0 @ L_1 ) ) ) @ ( produc235638504on_val @ E_3 @ ( produc755559506on_val @ H @ ( map_ad325961431ar_val @ L_0 @ L ) ) ) ) @ ( transi2118771717on_val @ ( red @ P ) ) ) ) )).

thf(fact_81_split__paired__Ex,axiom,(
    ! [P_6: produc652964533on_val > $o] :
      ( ( ?? @ produc652964533on_val @ P_6 )
    <=> ? [A_13: produc1746408499on_val,B_3: produc1746408499on_val] :
          ( P_6 @ ( produc345758123on_val @ A_13 @ B_3 ) ) ) )).

thf(fact_82_split__paired__Ex,axiom,(
    ! [P_6: produc1581780743on_val > $o] :
      ( ( ?? @ produc1581780743on_val @ P_6 )
    <=> ? [A_13: produc2090907612on_val,B_3: produc2090907612on_val] :
          ( P_6 @ ( produc259392253on_val @ A_13 @ B_3 ) ) ) )).

thf(fact_83_split__paired__Ex,axiom,(
    ! [P_6: produc2090907612on_val > $o] :
      ( ( ?? @ produc2090907612on_val @ P_6 )
    <=> ? [A_13: nat > option1728594148on_val,B_3: list_char > option_val] :
          ( P_6 @ ( produc755559506on_val @ A_13 @ B_3 ) ) ) )).

thf(fact_84_split__paired__Ex,axiom,(
    ! [P_6: produc1746408499on_val > $o] :
      ( ( ?? @ produc1746408499on_val @ P_6 )
    <=> ? [A_13: produc1282892786on_val,B_3: produc1282892786on_val] :
          ( P_6 @ ( produc833389609on_val @ A_13 @ B_3 ) ) ) )).

thf(fact_85_split__paired__Ex,axiom,(
    ! [P_6: produc1282892786on_val > $o] :
      ( ( ?? @ produc1282892786on_val @ P_6 )
    <=> ? [A_13: exp_list_char,B_3: produc2090907612on_val] :
          ( P_6 @ ( produc235638504on_val @ A_13 @ B_3 ) ) ) )).

thf(fact_86_FAccReds,axiom,(
    ! [F: list_char,D: list_char,E: exp_list_char,S_1: produc2090907612on_val,E_3: exp_list_char,S: produc2090907612on_val,P: list_P1999446415t_char] :
      ( ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ E @ S_1 ) @ ( produc235638504on_val @ E_3 @ S ) ) @ ( transi2118771717on_val @ ( red @ P ) ) )
     => ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ ( fAcc_list_char @ E @ F @ D ) @ S_1 ) @ ( produc235638504on_val @ ( fAcc_list_char @ E_3 @ F @ D ) @ S ) ) @ ( transi2118771717on_val @ ( red @ P ) ) ) ) )).

thf(fact_87_FAssReds1,axiom,(
    ! [F: list_char,D: list_char,E_2: exp_list_char,E: exp_list_char,S_1: produc2090907612on_val,E_3: exp_list_char,S: produc2090907612on_val,P: list_P1999446415t_char] :
      ( ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ E @ S_1 ) @ ( produc235638504on_val @ E_3 @ S ) ) @ ( transi2118771717on_val @ ( red @ P ) ) )
     => ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ ( fAss_list_char @ E @ F @ D @ E_2 ) @ S_1 ) @ ( produc235638504on_val @ ( fAss_list_char @ E_3 @ F @ D @ E_2 ) @ S ) ) @ ( transi2118771717on_val @ ( red @ P ) ) ) ) )).

thf(fact_88_rtrancl_Ortrancl__refl,axiom,(
    ! [A_17: produc1746408499on_val,R_12: produc652964533on_val > $o] :
      ( member1714424482on_val @ ( produc345758123on_val @ A_17 @ A_17 ) @ ( transi130214086on_val @ R_12 ) ) )).

thf(fact_89_rtrancl_Ortrancl__refl,axiom,(
    ! [A_17: produc2090907612on_val,R_12: produc1581780743on_val > $o] :
      ( member565037556on_val @ ( produc259392253on_val @ A_17 @ A_17 ) @ ( transi466770671on_val @ R_12 ) ) )).

thf(fact_90_rtrancl_Ortrancl__refl,axiom,(
    ! [A_17: produc1282892786on_val,R_12: produc1746408499on_val > $o] :
      ( member1913460000on_val @ ( produc833389609on_val @ A_17 @ A_17 ) @ ( transi2118771717on_val @ R_12 ) ) )).

thf(fact_91_r__into__rtrancl,axiom,(
    ! [P_5: produc652964533on_val,R_11: produc652964533on_val > $o] :
      ( ( member1714424482on_val @ P_5 @ R_11 )
     => ( member1714424482on_val @ P_5 @ ( transi130214086on_val @ R_11 ) ) ) )).

thf(fact_92_r__into__rtrancl,axiom,(
    ! [P_5: produc1581780743on_val,R_11: produc1581780743on_val > $o] :
      ( ( member565037556on_val @ P_5 @ R_11 )
     => ( member565037556on_val @ P_5 @ ( transi466770671on_val @ R_11 ) ) ) )).

thf(fact_93_r__into__rtrancl,axiom,(
    ! [P_5: produc1746408499on_val,R_11: produc1746408499on_val > $o] :
      ( ( member1913460000on_val @ P_5 @ R_11 )
     => ( member1913460000on_val @ P_5 @ ( transi2118771717on_val @ R_11 ) ) ) )).

thf(fact_94_rtrancl__idemp,axiom,(
    ! [R_10: produc652964533on_val > $o] :
      ( ( transi130214086on_val @ ( transi130214086on_val @ R_10 ) )
      = ( transi130214086on_val @ R_10 ) ) )).

thf(fact_95_rtrancl__idemp,axiom,(
    ! [R_10: produc1581780743on_val > $o] :
      ( ( transi466770671on_val @ ( transi466770671on_val @ R_10 ) )
      = ( transi466770671on_val @ R_10 ) ) )).

thf(fact_96_rtrancl__idemp,axiom,(
    ! [R_10: produc1746408499on_val > $o] :
      ( ( transi2118771717on_val @ ( transi2118771717on_val @ R_10 ) )
      = ( transi2118771717on_val @ R_10 ) ) )).

thf(fact_97_converse__rtrancl__into__rtrancl,axiom,(
    ! [C_3: produc1746408499on_val,A_16: produc1746408499on_val,B_6: produc1746408499on_val,R_9: produc652964533on_val > $o] :
      ( ( member1714424482on_val @ ( produc345758123on_val @ A_16 @ B_6 ) @ R_9 )
     => ( ( member1714424482on_val @ ( produc345758123on_val @ B_6 @ C_3 ) @ ( transi130214086on_val @ R_9 ) )
       => ( member1714424482on_val @ ( produc345758123on_val @ A_16 @ C_3 ) @ ( transi130214086on_val @ R_9 ) ) ) ) )).

thf(fact_98_converse__rtrancl__into__rtrancl,axiom,(
    ! [C_3: produc2090907612on_val,A_16: produc2090907612on_val,B_6: produc2090907612on_val,R_9: produc1581780743on_val > $o] :
      ( ( member565037556on_val @ ( produc259392253on_val @ A_16 @ B_6 ) @ R_9 )
     => ( ( member565037556on_val @ ( produc259392253on_val @ B_6 @ C_3 ) @ ( transi466770671on_val @ R_9 ) )
       => ( member565037556on_val @ ( produc259392253on_val @ A_16 @ C_3 ) @ ( transi466770671on_val @ R_9 ) ) ) ) )).

thf(fact_99_converse__rtrancl__into__rtrancl,axiom,(
    ! [C_3: produc1282892786on_val,A_16: produc1282892786on_val,B_6: produc1282892786on_val,R_9: produc1746408499on_val > $o] :
      ( ( member1913460000on_val @ ( produc833389609on_val @ A_16 @ B_6 ) @ R_9 )
     => ( ( member1913460000on_val @ ( produc833389609on_val @ B_6 @ C_3 ) @ ( transi2118771717on_val @ R_9 ) )
       => ( member1913460000on_val @ ( produc833389609on_val @ A_16 @ C_3 ) @ ( transi2118771717on_val @ R_9 ) ) ) ) )).

thf(fact_100_rtrancl_Ortrancl__into__rtrancl,axiom,(
    ! [C_2: produc1746408499on_val,A_15: produc1746408499on_val,B_5: produc1746408499on_val,R_8: produc652964533on_val > $o] :
      ( ( member1714424482on_val @ ( produc345758123on_val @ A_15 @ B_5 ) @ ( transi130214086on_val @ R_8 ) )
     => ( ( member1714424482on_val @ ( produc345758123on_val @ B_5 @ C_2 ) @ R_8 )
       => ( member1714424482on_val @ ( produc345758123on_val @ A_15 @ C_2 ) @ ( transi130214086on_val @ R_8 ) ) ) ) )).

thf(fact_101_rtrancl_Ortrancl__into__rtrancl,axiom,(
    ! [C_2: produc2090907612on_val,A_15: produc2090907612on_val,B_5: produc2090907612on_val,R_8: produc1581780743on_val > $o] :
      ( ( member565037556on_val @ ( produc259392253on_val @ A_15 @ B_5 ) @ ( transi466770671on_val @ R_8 ) )
     => ( ( member565037556on_val @ ( produc259392253on_val @ B_5 @ C_2 ) @ R_8 )
       => ( member565037556on_val @ ( produc259392253on_val @ A_15 @ C_2 ) @ ( transi466770671on_val @ R_8 ) ) ) ) )).

thf(fact_102_rtrancl_Ortrancl__into__rtrancl,axiom,(
    ! [C_2: produc1282892786on_val,A_15: produc1282892786on_val,B_5: produc1282892786on_val,R_8: produc1746408499on_val > $o] :
      ( ( member1913460000on_val @ ( produc833389609on_val @ A_15 @ B_5 ) @ ( transi2118771717on_val @ R_8 ) )
     => ( ( member1913460000on_val @ ( produc833389609on_val @ B_5 @ C_2 ) @ R_8 )
       => ( member1913460000on_val @ ( produc833389609on_val @ A_15 @ C_2 ) @ ( transi2118771717on_val @ R_8 ) ) ) ) )).

thf(fact_103_rtrancl__trans,axiom,(
    ! [C_1: produc1746408499on_val,A_14: produc1746408499on_val,B_4: produc1746408499on_val,R_7: produc652964533on_val > $o] :
      ( ( member1714424482on_val @ ( produc345758123on_val @ A_14 @ B_4 ) @ ( transi130214086on_val @ R_7 ) )
     => ( ( member1714424482on_val @ ( produc345758123on_val @ B_4 @ C_1 ) @ ( transi130214086on_val @ R_7 ) )
       => ( member1714424482on_val @ ( produc345758123on_val @ A_14 @ C_1 ) @ ( transi130214086on_val @ R_7 ) ) ) ) )).

thf(fact_104_rtrancl__trans,axiom,(
    ! [C_1: produc2090907612on_val,A_14: produc2090907612on_val,B_4: produc2090907612on_val,R_7: produc1581780743on_val > $o] :
      ( ( member565037556on_val @ ( produc259392253on_val @ A_14 @ B_4 ) @ ( transi466770671on_val @ R_7 ) )
     => ( ( member565037556on_val @ ( produc259392253on_val @ B_4 @ C_1 ) @ ( transi466770671on_val @ R_7 ) )
       => ( member565037556on_val @ ( produc259392253on_val @ A_14 @ C_1 ) @ ( transi466770671on_val @ R_7 ) ) ) ) )).

thf(fact_105_rtrancl__trans,axiom,(
    ! [C_1: produc1282892786on_val,A_14: produc1282892786on_val,B_4: produc1282892786on_val,R_7: produc1746408499on_val > $o] :
      ( ( member1913460000on_val @ ( produc833389609on_val @ A_14 @ B_4 ) @ ( transi2118771717on_val @ R_7 ) )
     => ( ( member1913460000on_val @ ( produc833389609on_val @ B_4 @ C_1 ) @ ( transi2118771717on_val @ R_7 ) )
       => ( member1913460000on_val @ ( produc833389609on_val @ A_14 @ C_1 ) @ ( transi2118771717on_val @ R_7 ) ) ) ) )).

thf(fact_106_converse__rtranclE2,axiom,(
    ! [Xa: produc1746408499on_val,Xb: produc1746408499on_val,Za: produc1746408499on_val,Zb: produc1746408499on_val,R_6: produc1206428857on_val > $o] :
      ( ( member1735092902on_val @ ( produc900610479on_val @ ( produc345758123on_val @ Xa @ Xb ) @ ( produc345758123on_val @ Za @ Zb ) ) @ ( transi1461661768on_val @ R_6 ) )
     => ( ( ( produc345758123on_val @ Xa @ Xb )
         != ( produc345758123on_val @ Za @ Zb ) )
       => ~ ( ! [A_13: produc1746408499on_val,B_3: produc1746408499on_val] :
                ( ( member1735092902on_val @ ( produc900610479on_val @ ( produc345758123on_val @ Xa @ Xb ) @ ( produc345758123on_val @ A_13 @ B_3 ) ) @ R_6 )
               => ~ ( member1735092902on_val @ ( produc900610479on_val @ ( produc345758123on_val @ A_13 @ B_3 ) @ ( produc345758123on_val @ Za @ Zb ) ) @ ( transi1461661768on_val @ R_6 ) ) ) ) ) ) )).

thf(fact_107_converse__rtranclE2,axiom,(
    ! [Xa: produc2090907612on_val,Xb: produc2090907612on_val,Za: produc2090907612on_val,Zb: produc2090907612on_val,R_6: produc93741661on_val > $o] :
      ( ( member1519152714on_val @ ( produc60772691on_val @ ( produc259392253on_val @ Xa @ Xb ) @ ( produc259392253on_val @ Za @ Zb ) ) @ ( transi289221018on_val @ R_6 ) )
     => ( ( ( produc259392253on_val @ Xa @ Xb )
         != ( produc259392253on_val @ Za @ Zb ) )
       => ~ ( ! [A_13: produc2090907612on_val,B_3: produc2090907612on_val] :
                ( ( member1519152714on_val @ ( produc60772691on_val @ ( produc259392253on_val @ Xa @ Xb ) @ ( produc259392253on_val @ A_13 @ B_3 ) ) @ R_6 )
               => ~ ( member1519152714on_val @ ( produc60772691on_val @ ( produc259392253on_val @ A_13 @ B_3 ) @ ( produc259392253on_val @ Za @ Zb ) ) @ ( transi289221018on_val @ R_6 ) ) ) ) ) ) )).

thf(fact_108_converse__rtranclE2,axiom,(
    ! [Xa: nat > option1728594148on_val,Xb: list_char > option_val,Za: nat > option1728594148on_val,Zb: list_char > option_val,R_6: produc1581780743on_val > $o] :
      ( ( member565037556on_val @ ( produc259392253on_val @ ( produc755559506on_val @ Xa @ Xb ) @ ( produc755559506on_val @ Za @ Zb ) ) @ ( transi466770671on_val @ R_6 ) )
     => ( ( ( produc755559506on_val @ Xa @ Xb )
         != ( produc755559506on_val @ Za @ Zb ) )
       => ~ ( ! [A_13: nat > option1728594148on_val,B_3: list_char > option_val] :
                ( ( member565037556on_val @ ( produc259392253on_val @ ( produc755559506on_val @ Xa @ Xb ) @ ( produc755559506on_val @ A_13 @ B_3 ) ) @ R_6 )
               => ~ ( member565037556on_val @ ( produc259392253on_val @ ( produc755559506on_val @ A_13 @ B_3 ) @ ( produc755559506on_val @ Za @ Zb ) ) @ ( transi466770671on_val @ R_6 ) ) ) ) ) ) )).

thf(fact_109_converse__rtranclE2,axiom,(
    ! [Xa: produc1282892786on_val,Xb: produc1282892786on_val,Za: produc1282892786on_val,Zb: produc1282892786on_val,R_6: produc652964533on_val > $o] :
      ( ( member1714424482on_val @ ( produc345758123on_val @ ( produc833389609on_val @ Xa @ Xb ) @ ( produc833389609on_val @ Za @ Zb ) ) @ ( transi130214086on_val @ R_6 ) )
     => ( ( ( produc833389609on_val @ Xa @ Xb )
         != ( produc833389609on_val @ Za @ Zb ) )
       => ~ ( ! [A_13: produc1282892786on_val,B_3: produc1282892786on_val] :
                ( ( member1714424482on_val @ ( produc345758123on_val @ ( produc833389609on_val @ Xa @ Xb ) @ ( produc833389609on_val @ A_13 @ B_3 ) ) @ R_6 )
               => ~ ( member1714424482on_val @ ( produc345758123on_val @ ( produc833389609on_val @ A_13 @ B_3 ) @ ( produc833389609on_val @ Za @ Zb ) ) @ ( transi130214086on_val @ R_6 ) ) ) ) ) ) )).

thf(fact_110_converse__rtranclE2,axiom,(
    ! [Xa: exp_list_char,Xb: produc2090907612on_val,Za: exp_list_char,Zb: produc2090907612on_val,R_6: produc1746408499on_val > $o] :
      ( ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ Xa @ Xb ) @ ( produc235638504on_val @ Za @ Zb ) ) @ ( transi2118771717on_val @ R_6 ) )
     => ( ( ( produc235638504on_val @ Xa @ Xb )
         != ( produc235638504on_val @ Za @ Zb ) )
       => ~ ( ! [A_13: exp_list_char,B_3: produc2090907612on_val] :
                ( ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ Xa @ Xb ) @ ( produc235638504on_val @ A_13 @ B_3 ) ) @ R_6 )
               => ~ ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ A_13 @ B_3 ) @ ( produc235638504on_val @ Za @ Zb ) ) @ ( transi2118771717on_val @ R_6 ) ) ) ) ) ) )).

thf(fact_111_converse__rtrancl__induct2,axiom,(
    ! [P_4: produc1746408499on_val > produc1746408499on_val > $o,Ax_1: produc1746408499on_val,Ay_1: produc1746408499on_val,Bx_1: produc1746408499on_val,By_1: produc1746408499on_val,R_5: produc1206428857on_val > $o] :
      ( ( member1735092902on_val @ ( produc900610479on_val @ ( produc345758123on_val @ Ax_1 @ Ay_1 ) @ ( produc345758123on_val @ Bx_1 @ By_1 ) ) @ ( transi1461661768on_val @ R_5 ) )
     => ( ( P_4 @ Bx_1 @ By_1 )
       => ( ! [A_13: produc1746408499on_val,B_3: produc1746408499on_val,Aa: produc1746408499on_val,Ba: produc1746408499on_val] :
              ( ( member1735092902on_val @ ( produc900610479on_val @ ( produc345758123on_val @ A_13 @ B_3 ) @ ( produc345758123on_val @ Aa @ Ba ) ) @ R_5 )
             => ( ( member1735092902on_val @ ( produc900610479on_val @ ( produc345758123on_val @ Aa @ Ba ) @ ( produc345758123on_val @ Bx_1 @ By_1 ) ) @ ( transi1461661768on_val @ R_5 ) )
               => ( ( P_4 @ Aa @ Ba )
                 => ( P_4 @ A_13 @ B_3 ) ) ) )
         => ( P_4 @ Ax_1 @ Ay_1 ) ) ) ) )).

thf(fact_112_converse__rtrancl__induct2,axiom,(
    ! [P_4: produc2090907612on_val > produc2090907612on_val > $o,Ax_1: produc2090907612on_val,Ay_1: produc2090907612on_val,Bx_1: produc2090907612on_val,By_1: produc2090907612on_val,R_5: produc93741661on_val > $o] :
      ( ( member1519152714on_val @ ( produc60772691on_val @ ( produc259392253on_val @ Ax_1 @ Ay_1 ) @ ( produc259392253on_val @ Bx_1 @ By_1 ) ) @ ( transi289221018on_val @ R_5 ) )
     => ( ( P_4 @ Bx_1 @ By_1 )
       => ( ! [A_13: produc2090907612on_val,B_3: produc2090907612on_val,Aa: produc2090907612on_val,Ba: produc2090907612on_val] :
              ( ( member1519152714on_val @ ( produc60772691on_val @ ( produc259392253on_val @ A_13 @ B_3 ) @ ( produc259392253on_val @ Aa @ Ba ) ) @ R_5 )
             => ( ( member1519152714on_val @ ( produc60772691on_val @ ( produc259392253on_val @ Aa @ Ba ) @ ( produc259392253on_val @ Bx_1 @ By_1 ) ) @ ( transi289221018on_val @ R_5 ) )
               => ( ( P_4 @ Aa @ Ba )
                 => ( P_4 @ A_13 @ B_3 ) ) ) )
         => ( P_4 @ Ax_1 @ Ay_1 ) ) ) ) )).

thf(fact_113_converse__rtrancl__induct2,axiom,(
    ! [P_4: ( nat > option1728594148on_val ) > ( list_char > option_val ) > $o,Ax_1: nat > option1728594148on_val,Ay_1: list_char > option_val,Bx_1: nat > option1728594148on_val,By_1: list_char > option_val,R_5: produc1581780743on_val > $o] :
      ( ( member565037556on_val @ ( produc259392253on_val @ ( produc755559506on_val @ Ax_1 @ Ay_1 ) @ ( produc755559506on_val @ Bx_1 @ By_1 ) ) @ ( transi466770671on_val @ R_5 ) )
     => ( ( P_4 @ Bx_1 @ By_1 )
       => ( ! [A_13: nat > option1728594148on_val,B_3: list_char > option_val,Aa: nat > option1728594148on_val,Ba: list_char > option_val] :
              ( ( member565037556on_val @ ( produc259392253on_val @ ( produc755559506on_val @ A_13 @ B_3 ) @ ( produc755559506on_val @ Aa @ Ba ) ) @ R_5 )
             => ( ( member565037556on_val @ ( produc259392253on_val @ ( produc755559506on_val @ Aa @ Ba ) @ ( produc755559506on_val @ Bx_1 @ By_1 ) ) @ ( transi466770671on_val @ R_5 ) )
               => ( ( P_4 @ Aa @ Ba )
                 => ( P_4 @ A_13 @ B_3 ) ) ) )
         => ( P_4 @ Ax_1 @ Ay_1 ) ) ) ) )).

thf(fact_114_converse__rtrancl__induct2,axiom,(
    ! [P_4: produc1282892786on_val > produc1282892786on_val > $o,Ax_1: produc1282892786on_val,Ay_1: produc1282892786on_val,Bx_1: produc1282892786on_val,By_1: produc1282892786on_val,R_5: produc652964533on_val > $o] :
      ( ( member1714424482on_val @ ( produc345758123on_val @ ( produc833389609on_val @ Ax_1 @ Ay_1 ) @ ( produc833389609on_val @ Bx_1 @ By_1 ) ) @ ( transi130214086on_val @ R_5 ) )
     => ( ( P_4 @ Bx_1 @ By_1 )
       => ( ! [A_13: produc1282892786on_val,B_3: produc1282892786on_val,Aa: produc1282892786on_val,Ba: produc1282892786on_val] :
              ( ( member1714424482on_val @ ( produc345758123on_val @ ( produc833389609on_val @ A_13 @ B_3 ) @ ( produc833389609on_val @ Aa @ Ba ) ) @ R_5 )
             => ( ( member1714424482on_val @ ( produc345758123on_val @ ( produc833389609on_val @ Aa @ Ba ) @ ( produc833389609on_val @ Bx_1 @ By_1 ) ) @ ( transi130214086on_val @ R_5 ) )
               => ( ( P_4 @ Aa @ Ba )
                 => ( P_4 @ A_13 @ B_3 ) ) ) )
         => ( P_4 @ Ax_1 @ Ay_1 ) ) ) ) )).

thf(fact_115_converse__rtrancl__induct2,axiom,(
    ! [P_4: exp_list_char > produc2090907612on_val > $o,Ax_1: exp_list_char,Ay_1: produc2090907612on_val,Bx_1: exp_list_char,By_1: produc2090907612on_val,R_5: produc1746408499on_val > $o] :
      ( ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ Ax_1 @ Ay_1 ) @ ( produc235638504on_val @ Bx_1 @ By_1 ) ) @ ( transi2118771717on_val @ R_5 ) )
     => ( ( P_4 @ Bx_1 @ By_1 )
       => ( ! [A_13: exp_list_char,B_3: produc2090907612on_val,Aa: exp_list_char,Ba: produc2090907612on_val] :
              ( ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ A_13 @ B_3 ) @ ( produc235638504on_val @ Aa @ Ba ) ) @ R_5 )
             => ( ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ Aa @ Ba ) @ ( produc235638504on_val @ Bx_1 @ By_1 ) ) @ ( transi2118771717on_val @ R_5 ) )
               => ( ( P_4 @ Aa @ Ba )
                 => ( P_4 @ A_13 @ B_3 ) ) ) )
         => ( P_4 @ Ax_1 @ Ay_1 ) ) ) ) )).

thf(fact_116_rtrancl__induct2,axiom,(
    ! [P_3: produc1746408499on_val > produc1746408499on_val > $o,Ax: produc1746408499on_val,Ay: produc1746408499on_val,Bx: produc1746408499on_val,By: produc1746408499on_val,R_4: produc1206428857on_val > $o] :
      ( ( member1735092902on_val @ ( produc900610479on_val @ ( produc345758123on_val @ Ax @ Ay ) @ ( produc345758123on_val @ Bx @ By ) ) @ ( transi1461661768on_val @ R_4 ) )
     => ( ( P_3 @ Ax @ Ay )
       => ( ! [A_13: produc1746408499on_val,B_3: produc1746408499on_val,Aa: produc1746408499on_val,Ba: produc1746408499on_val] :
              ( ( member1735092902on_val @ ( produc900610479on_val @ ( produc345758123on_val @ Ax @ Ay ) @ ( produc345758123on_val @ A_13 @ B_3 ) ) @ ( transi1461661768on_val @ R_4 ) )
             => ( ( member1735092902on_val @ ( produc900610479on_val @ ( produc345758123on_val @ A_13 @ B_3 ) @ ( produc345758123on_val @ Aa @ Ba ) ) @ R_4 )
               => ( ( P_3 @ A_13 @ B_3 )
                 => ( P_3 @ Aa @ Ba ) ) ) )
         => ( P_3 @ Bx @ By ) ) ) ) )).

thf(fact_117_rtrancl__induct2,axiom,(
    ! [P_3: produc2090907612on_val > produc2090907612on_val > $o,Ax: produc2090907612on_val,Ay: produc2090907612on_val,Bx: produc2090907612on_val,By: produc2090907612on_val,R_4: produc93741661on_val > $o] :
      ( ( member1519152714on_val @ ( produc60772691on_val @ ( produc259392253on_val @ Ax @ Ay ) @ ( produc259392253on_val @ Bx @ By ) ) @ ( transi289221018on_val @ R_4 ) )
     => ( ( P_3 @ Ax @ Ay )
       => ( ! [A_13: produc2090907612on_val,B_3: produc2090907612on_val,Aa: produc2090907612on_val,Ba: produc2090907612on_val] :
              ( ( member1519152714on_val @ ( produc60772691on_val @ ( produc259392253on_val @ Ax @ Ay ) @ ( produc259392253on_val @ A_13 @ B_3 ) ) @ ( transi289221018on_val @ R_4 ) )
             => ( ( member1519152714on_val @ ( produc60772691on_val @ ( produc259392253on_val @ A_13 @ B_3 ) @ ( produc259392253on_val @ Aa @ Ba ) ) @ R_4 )
               => ( ( P_3 @ A_13 @ B_3 )
                 => ( P_3 @ Aa @ Ba ) ) ) )
         => ( P_3 @ Bx @ By ) ) ) ) )).

thf(fact_118_rtrancl__induct2,axiom,(
    ! [P_3: ( nat > option1728594148on_val ) > ( list_char > option_val ) > $o,Ax: nat > option1728594148on_val,Ay: list_char > option_val,Bx: nat > option1728594148on_val,By: list_char > option_val,R_4: produc1581780743on_val > $o] :
      ( ( member565037556on_val @ ( produc259392253on_val @ ( produc755559506on_val @ Ax @ Ay ) @ ( produc755559506on_val @ Bx @ By ) ) @ ( transi466770671on_val @ R_4 ) )
     => ( ( P_3 @ Ax @ Ay )
       => ( ! [A_13: nat > option1728594148on_val,B_3: list_char > option_val,Aa: nat > option1728594148on_val,Ba: list_char > option_val] :
              ( ( member565037556on_val @ ( produc259392253on_val @ ( produc755559506on_val @ Ax @ Ay ) @ ( produc755559506on_val @ A_13 @ B_3 ) ) @ ( transi466770671on_val @ R_4 ) )
             => ( ( member565037556on_val @ ( produc259392253on_val @ ( produc755559506on_val @ A_13 @ B_3 ) @ ( produc755559506on_val @ Aa @ Ba ) ) @ R_4 )
               => ( ( P_3 @ A_13 @ B_3 )
                 => ( P_3 @ Aa @ Ba ) ) ) )
         => ( P_3 @ Bx @ By ) ) ) ) )).

thf(fact_119_rtrancl__induct2,axiom,(
    ! [P_3: produc1282892786on_val > produc1282892786on_val > $o,Ax: produc1282892786on_val,Ay: produc1282892786on_val,Bx: produc1282892786on_val,By: produc1282892786on_val,R_4: produc652964533on_val > $o] :
      ( ( member1714424482on_val @ ( produc345758123on_val @ ( produc833389609on_val @ Ax @ Ay ) @ ( produc833389609on_val @ Bx @ By ) ) @ ( transi130214086on_val @ R_4 ) )
     => ( ( P_3 @ Ax @ Ay )
       => ( ! [A_13: produc1282892786on_val,B_3: produc1282892786on_val,Aa: produc1282892786on_val,Ba: produc1282892786on_val] :
              ( ( member1714424482on_val @ ( produc345758123on_val @ ( produc833389609on_val @ Ax @ Ay ) @ ( produc833389609on_val @ A_13 @ B_3 ) ) @ ( transi130214086on_val @ R_4 ) )
             => ( ( member1714424482on_val @ ( produc345758123on_val @ ( produc833389609on_val @ A_13 @ B_3 ) @ ( produc833389609on_val @ Aa @ Ba ) ) @ R_4 )
               => ( ( P_3 @ A_13 @ B_3 )
                 => ( P_3 @ Aa @ Ba ) ) ) )
         => ( P_3 @ Bx @ By ) ) ) ) )).

thf(fact_120_rtrancl__induct2,axiom,(
    ! [P_3: exp_list_char > produc2090907612on_val > $o,Ax: exp_list_char,Ay: produc2090907612on_val,Bx: exp_list_char,By: produc2090907612on_val,R_4: produc1746408499on_val > $o] :
      ( ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ Ax @ Ay ) @ ( produc235638504on_val @ Bx @ By ) ) @ ( transi2118771717on_val @ R_4 ) )
     => ( ( P_3 @ Ax @ Ay )
       => ( ! [A_13: exp_list_char,B_3: produc2090907612on_val,Aa: exp_list_char,Ba: produc2090907612on_val] :
              ( ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ Ax @ Ay ) @ ( produc235638504on_val @ A_13 @ B_3 ) ) @ ( transi2118771717on_val @ R_4 ) )
             => ( ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ A_13 @ B_3 ) @ ( produc235638504on_val @ Aa @ Ba ) ) @ R_4 )
               => ( ( P_3 @ A_13 @ B_3 )
                 => ( P_3 @ Aa @ Ba ) ) ) )
         => ( P_3 @ Bx @ By ) ) ) ) )).

thf(fact_121_rtranclE,axiom,(
    ! [A_12: produc1746408499on_val,B_2: produc1746408499on_val,R_3: produc652964533on_val > $o] :
      ( ( member1714424482on_val @ ( produc345758123on_val @ A_12 @ B_2 ) @ ( transi130214086on_val @ R_3 ) )
     => ( ( A_12 != B_2 )
       => ~ ( ! [Y: produc1746408499on_val] :
                ( ( member1714424482on_val @ ( produc345758123on_val @ A_12 @ Y ) @ ( transi130214086on_val @ R_3 ) )
               => ~ ( member1714424482on_val @ ( produc345758123on_val @ Y @ B_2 ) @ R_3 ) ) ) ) ) )).

thf(fact_122_rtranclE,axiom,(
    ! [A_12: produc2090907612on_val,B_2: produc2090907612on_val,R_3: produc1581780743on_val > $o] :
      ( ( member565037556on_val @ ( produc259392253on_val @ A_12 @ B_2 ) @ ( transi466770671on_val @ R_3 ) )
     => ( ( A_12 != B_2 )
       => ~ ( ! [Y: produc2090907612on_val] :
                ( ( member565037556on_val @ ( produc259392253on_val @ A_12 @ Y ) @ ( transi466770671on_val @ R_3 ) )
               => ~ ( member565037556on_val @ ( produc259392253on_val @ Y @ B_2 ) @ R_3 ) ) ) ) ) )).

thf(fact_123_rtranclE,axiom,(
    ! [A_12: produc1282892786on_val,B_2: produc1282892786on_val,R_3: produc1746408499on_val > $o] :
      ( ( member1913460000on_val @ ( produc833389609on_val @ A_12 @ B_2 ) @ ( transi2118771717on_val @ R_3 ) )
     => ( ( A_12 != B_2 )
       => ~ ( ! [Y: produc1282892786on_val] :
                ( ( member1913460000on_val @ ( produc833389609on_val @ A_12 @ Y ) @ ( transi2118771717on_val @ R_3 ) )
               => ~ ( member1913460000on_val @ ( produc833389609on_val @ Y @ B_2 ) @ R_3 ) ) ) ) ) )).

thf(fact_124_converse__rtranclE,axiom,(
    ! [X_1: produc1746408499on_val,Z_1: produc1746408499on_val,R_2: produc652964533on_val > $o] :
      ( ( member1714424482on_val @ ( produc345758123on_val @ X_1 @ Z_1 ) @ ( transi130214086on_val @ R_2 ) )
     => ( ( X_1 != Z_1 )
       => ~ ( ! [Y: produc1746408499on_val] :
                ( ( member1714424482on_val @ ( produc345758123on_val @ X_1 @ Y ) @ R_2 )
               => ~ ( member1714424482on_val @ ( produc345758123on_val @ Y @ Z_1 ) @ ( transi130214086on_val @ R_2 ) ) ) ) ) ) )).

thf(fact_125_converse__rtranclE,axiom,(
    ! [X_1: produc2090907612on_val,Z_1: produc2090907612on_val,R_2: produc1581780743on_val > $o] :
      ( ( member565037556on_val @ ( produc259392253on_val @ X_1 @ Z_1 ) @ ( transi466770671on_val @ R_2 ) )
     => ( ( X_1 != Z_1 )
       => ~ ( ! [Y: produc2090907612on_val] :
                ( ( member565037556on_val @ ( produc259392253on_val @ X_1 @ Y ) @ R_2 )
               => ~ ( member565037556on_val @ ( produc259392253on_val @ Y @ Z_1 ) @ ( transi466770671on_val @ R_2 ) ) ) ) ) ) )).

thf(fact_126_converse__rtranclE,axiom,(
    ! [X_1: produc1282892786on_val,Z_1: produc1282892786on_val,R_2: produc1746408499on_val > $o] :
      ( ( member1913460000on_val @ ( produc833389609on_val @ X_1 @ Z_1 ) @ ( transi2118771717on_val @ R_2 ) )
     => ( ( X_1 != Z_1 )
       => ~ ( ! [Y: produc1282892786on_val] :
                ( ( member1913460000on_val @ ( produc833389609on_val @ X_1 @ Y ) @ R_2 )
               => ~ ( member1913460000on_val @ ( produc833389609on_val @ Y @ Z_1 ) @ ( transi2118771717on_val @ R_2 ) ) ) ) ) ) )).

thf(fact_127_converse__rtrancl__induct,axiom,(
    ! [P_2: produc1746408499on_val > $o,A_11: produc1746408499on_val,B_1: produc1746408499on_val,R_1: produc652964533on_val > $o] :
      ( ( member1714424482on_val @ ( produc345758123on_val @ A_11 @ B_1 ) @ ( transi130214086on_val @ R_1 ) )
     => ( ( P_2 @ B_1 )
       => ( ! [Y: produc1746408499on_val,Z: produc1746408499on_val] :
              ( ( member1714424482on_val @ ( produc345758123on_val @ Y @ Z ) @ R_1 )
             => ( ( member1714424482on_val @ ( produc345758123on_val @ Z @ B_1 ) @ ( transi130214086on_val @ R_1 ) )
               => ( ( P_2 @ Z )
                 => ( P_2 @ Y ) ) ) )
         => ( P_2 @ A_11 ) ) ) ) )).

thf(fact_128_converse__rtrancl__induct,axiom,(
    ! [P_2: produc2090907612on_val > $o,A_11: produc2090907612on_val,B_1: produc2090907612on_val,R_1: produc1581780743on_val > $o] :
      ( ( member565037556on_val @ ( produc259392253on_val @ A_11 @ B_1 ) @ ( transi466770671on_val @ R_1 ) )
     => ( ( P_2 @ B_1 )
       => ( ! [Y: produc2090907612on_val,Z: produc2090907612on_val] :
              ( ( member565037556on_val @ ( produc259392253on_val @ Y @ Z ) @ R_1 )
             => ( ( member565037556on_val @ ( produc259392253on_val @ Z @ B_1 ) @ ( transi466770671on_val @ R_1 ) )
               => ( ( P_2 @ Z )
                 => ( P_2 @ Y ) ) ) )
         => ( P_2 @ A_11 ) ) ) ) )).

thf(fact_129_converse__rtrancl__induct,axiom,(
    ! [P_2: produc1282892786on_val > $o,A_11: produc1282892786on_val,B_1: produc1282892786on_val,R_1: produc1746408499on_val > $o] :
      ( ( member1913460000on_val @ ( produc833389609on_val @ A_11 @ B_1 ) @ ( transi2118771717on_val @ R_1 ) )
     => ( ( P_2 @ B_1 )
       => ( ! [Y: produc1282892786on_val,Z: produc1282892786on_val] :
              ( ( member1913460000on_val @ ( produc833389609on_val @ Y @ Z ) @ R_1 )
             => ( ( member1913460000on_val @ ( produc833389609on_val @ Z @ B_1 ) @ ( transi2118771717on_val @ R_1 ) )
               => ( ( P_2 @ Z )
                 => ( P_2 @ Y ) ) ) )
         => ( P_2 @ A_11 ) ) ) ) )).

thf(fact_130_rtrancl__induct,axiom,(
    ! [P_1: produc1746408499on_val > $o,A_10: produc1746408499on_val,B: produc1746408499on_val,R: produc652964533on_val > $o] :
      ( ( member1714424482on_val @ ( produc345758123on_val @ A_10 @ B ) @ ( transi130214086on_val @ R ) )
     => ( ( P_1 @ A_10 )
       => ( ! [Y: produc1746408499on_val,Z: produc1746408499on_val] :
              ( ( member1714424482on_val @ ( produc345758123on_val @ A_10 @ Y ) @ ( transi130214086on_val @ R ) )
             => ( ( member1714424482on_val @ ( produc345758123on_val @ Y @ Z ) @ R )
               => ( ( P_1 @ Y )
                 => ( P_1 @ Z ) ) ) )
         => ( P_1 @ B ) ) ) ) )).

thf(fact_131_rtrancl__induct,axiom,(
    ! [P_1: produc2090907612on_val > $o,A_10: produc2090907612on_val,B: produc2090907612on_val,R: produc1581780743on_val > $o] :
      ( ( member565037556on_val @ ( produc259392253on_val @ A_10 @ B ) @ ( transi466770671on_val @ R ) )
     => ( ( P_1 @ A_10 )
       => ( ! [Y: produc2090907612on_val,Z: produc2090907612on_val] :
              ( ( member565037556on_val @ ( produc259392253on_val @ A_10 @ Y ) @ ( transi466770671on_val @ R ) )
             => ( ( member565037556on_val @ ( produc259392253on_val @ Y @ Z ) @ R )
               => ( ( P_1 @ Y )
                 => ( P_1 @ Z ) ) ) )
         => ( P_1 @ B ) ) ) ) )).

thf(fact_132_rtrancl__induct,axiom,(
    ! [P_1: produc1282892786on_val > $o,A_10: produc1282892786on_val,B: produc1282892786on_val,R: produc1746408499on_val > $o] :
      ( ( member1913460000on_val @ ( produc833389609on_val @ A_10 @ B ) @ ( transi2118771717on_val @ R ) )
     => ( ( P_1 @ A_10 )
       => ( ! [Y: produc1282892786on_val,Z: produc1282892786on_val] :
              ( ( member1913460000on_val @ ( produc833389609on_val @ A_10 @ Y ) @ ( transi2118771717on_val @ R ) )
             => ( ( member1913460000on_val @ ( produc833389609on_val @ Y @ Z ) @ R )
               => ( ( P_1 @ Y )
                 => ( P_1 @ Z ) ) ) )
         => ( P_1 @ B ) ) ) ) )).

thf(fact_133_mem__def,axiom,(
    ! [X: produc652964533on_val,A_9: produc652964533on_val > $o] :
      ( ( member1714424482on_val @ X @ A_9 )
    <=> ( A_9 @ X ) ) )).

thf(fact_134_mem__def,axiom,(
    ! [X: produc1581780743on_val,A_9: produc1581780743on_val > $o] :
      ( ( member565037556on_val @ X @ A_9 )
    <=> ( A_9 @ X ) ) )).

thf(fact_135_mem__def,axiom,(
    ! [X: produc1282892786on_val,A_9: produc1282892786on_val > $o] :
      ( ( member1072200031on_val @ X @ A_9 )
    <=> ( A_9 @ X ) ) )).

thf(fact_136_mem__def,axiom,(
    ! [X: produc2090907612on_val,A_9: produc2090907612on_val > $o] :
      ( ( member1846553161on_val @ X @ A_9 )
    <=> ( A_9 @ X ) ) )).

thf(fact_137_mem__def,axiom,(
    ! [X: produc1746408499on_val,A_9: produc1746408499on_val > $o] :
      ( ( member1913460000on_val @ X @ A_9 )
    <=> ( A_9 @ X ) ) )).

thf(fact_138_FAssReds2,axiom,(
    ! [V: val,F: list_char,D: list_char,E: exp_list_char,S_1: produc2090907612on_val,E_3: exp_list_char,S: produc2090907612on_val,P: list_P1999446415t_char] :
      ( ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ E @ S_1 ) @ ( produc235638504on_val @ E_3 @ S ) ) @ ( transi2118771717on_val @ ( red @ P ) ) )
     => ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ ( fAss_list_char @ ( val_list_char @ V ) @ F @ D @ E ) @ S_1 ) @ ( produc235638504on_val @ ( fAss_list_char @ ( val_list_char @ V ) @ F @ D @ E_3 ) @ S ) ) @ ( transi2118771717on_val @ ( red @ P ) ) ) ) )).

thf(fact_139_exp_Osimps_I3_J,axiom,(
    ! [Val_9: val,Val_8: val] :
      ( ( ( val_list_char @ Val_9 )
        = ( val_list_char @ Val_8 ) )
    <=> ( Val_9 = Val_8 ) ) )).

thf(fact_140_exp_Osimps_I76_J,axiom,(
    ! [Val_7: val,Exp_14: exp_list_char,List1_11: list_char,List2_11: list_char] :
      ( ( val_list_char @ Val_7 )
     != ( fAcc_list_char @ Exp_14 @ List1_11 @ List2_11 ) ) )).

thf(fact_141_exp_Osimps_I77_J,axiom,(
    ! [Exp_13: exp_list_char,List1_10: list_char,List2_10: list_char,Val_6: val] :
      ( ( fAcc_list_char @ Exp_13 @ List1_10 @ List2_10 )
     != ( val_list_char @ Val_6 ) ) )).

thf(fact_142_exp_Osimps_I78_J,axiom,(
    ! [Val_5: val,Exp1_14: exp_list_char,List1_9: list_char,List2_9: list_char,Exp2_14: exp_list_char] :
      ( ( val_list_char @ Val_5 )
     != ( fAss_list_char @ Exp1_14 @ List1_9 @ List2_9 @ Exp2_14 ) ) )).

thf(fact_143_exp_Osimps_I79_J,axiom,(
    ! [Exp1_13: exp_list_char,List1_8: list_char,List2_8: list_char,Exp2_13: exp_list_char,Val_4: val] :
      ( ( fAss_list_char @ Exp1_13 @ List1_8 @ List2_8 @ Exp2_13 )
     != ( val_list_char @ Val_4 ) ) )).

thf(fact_144_red__reds_OFAssRed2,axiom,(
    ! [V: val,F: list_char,D: list_char,E: exp_list_char,S_1: produc2090907612on_val,E_3: exp_list_char,S: produc2090907612on_val,P: list_P1999446415t_char] :
      ( ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ E @ S_1 ) @ ( produc235638504on_val @ E_3 @ S ) ) @ ( red @ P ) )
     => ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ ( fAss_list_char @ ( val_list_char @ V ) @ F @ D @ E ) @ S_1 ) @ ( produc235638504on_val @ ( fAss_list_char @ ( val_list_char @ V ) @ F @ D @ E_3 ) @ S ) ) @ ( red @ P ) ) ) )).

thf(fact_145_FAssRedsThrow2,axiom,(
    ! [F: list_char,D: list_char,E_2: exp_list_char,E: exp_list_char,S_2: produc2090907612on_val,E_1: exp_list_char,S_0: produc2090907612on_val,V: val,S_1_1: produc2090907612on_val,P: list_P1999446415t_char] :
      ( ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ E_1 @ S_0 ) @ ( produc235638504on_val @ ( val_list_char @ V ) @ S_1_1 ) ) @ ( transi2118771717on_val @ ( red @ P ) ) )
     => ( ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ E_2 @ S_1_1 ) @ ( produc235638504on_val @ ( throw_list_char @ E ) @ S_2 ) ) @ ( transi2118771717on_val @ ( red @ P ) ) )
       => ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ ( fAss_list_char @ E_1 @ F @ D @ E_2 ) @ S_0 ) @ ( produc235638504on_val @ ( throw_list_char @ E ) @ S_2 ) ) @ ( transi2118771717on_val @ ( red @ P ) ) ) ) ) )).

thf(fact_146_TryRedsVal,axiom,(
    ! [C: list_char,V_1: list_char,E_2: exp_list_char,E: exp_list_char,S_1: produc2090907612on_val,V: val,S: produc2090907612on_val,P: list_P1999446415t_char] :
      ( ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ E @ S_1 ) @ ( produc235638504on_val @ ( val_list_char @ V ) @ S ) ) @ ( transi2118771717on_val @ ( red @ P ) ) )
     => ( member1913460000on_val @ ( produc833389609on_val @ ( produc235638504on_val @ ( tryCatch_list_char @ E @ C @ V_1 @ E_2 ) @ S_1 ) @ ( produc235638504on_val @ ( val_list_char @ V ) @ S ) ) @ ( transi2118771717on_val @ ( red @ P ) ) ) ) )).

thf(fact_147_exp_Osimps_I90_J,axiom,(
    ! [Val_3: val,Exp_12: exp_list_char] :
      ( ( val_list_char @ Val_3 )
     != ( throw_list_char @ Exp_12 ) ) )).

thf(fact_148_exp_Osimps_I91_J,axiom,(
    ! [Exp_11: exp_list_char,Val_2: val] :
      ( ( throw_list_char @ Exp_11 )
     != ( val_list_char @ Val_2 ) ) )).

thf(fact_149_exp_Osimps_I92_J,axiom,(
    ! [Val_1: val,Exp1_12: exp_list_char,List_8: list_char,A_8: list_char,Exp2_12: exp_list_char] :
      ( ( val_list_char @ Val_1 )
     != ( tryCatch_list_char @ Exp1_12 @ List_8 @ A_8 @ Exp2_12 ) ) )).

thf(fact_150_exp_Osimps_I93_J,axiom,(
    ! [Exp1_11: exp_list_char,List_7: list_char,A_7: list_char,Exp2_11: exp_list_char,Val: val] :
      ( ( tryCatch_list_char @ Exp1_11 @ List_7 @ A_7 @ Exp2_11 )
     != ( val_list_char @ Val ) ) )).

thf(fact_151_exp_Osimps_I180_J,axiom,(
    ! [Exp1_10: exp_list_char,List1_7: list_char,List2_7: list_char,Exp2_10: exp_list_char,Exp_10: exp_list_char] :
      ( ( fAss_list_char @ Exp1_10 @ List1_7 @ List2_7 @ Exp2_10 )
     != ( throw_list_char @ Exp_10 ) ) )).

thf(fact_152_exp_Osimps_I181_J,axiom,(
    ! [Exp_9: exp_list_char,Exp1_9: exp_list_char,List1_6: list_char,List2_6: list_char,Exp2_9: exp_list_char] :
      ( ( throw_list_char @ Exp_9 )
     != ( fAss_list_char @ Exp1_9 @ List1_6 @ List2_6 @ Exp2_9 ) ) )).

thf(fact_153_exp_Osimps_I166_J,axiom,(
    ! [Exp_8: exp_list_char,List1_5: list_char,List2_5: list_char,Exp_7: exp_list_char] :
      ( ( fAcc_list_char @ Exp_8 @ List1_5 @ List2_5 )
     != ( throw_list_char @ Exp_7 ) ) )).

thf(fact_154_exp_Osimps_I167_J,axiom,(
    ! [Exp_6: exp_list_char,Exp_5: exp_list_char,List1_4: list_char,List2_4: list_char] :
      ( ( throw_list_char @ Exp_6 )
     != ( fAcc_list_char @ Exp_5 @ List1_4 @ List2_4 ) ) )).

thf(fact_155_exp_Osimps_I183_J,axiom,(
    ! [Exp1_8: exp_list_char,List_6: list_char,A_6: list_char,Exp2_8: exp_list_char,Exp1_7: exp_list_char,List1_3: list_char,List2_3: list_char,Exp2_7: exp_list_char] :
      ( ( tryCatch_list_char @ Exp1_8 @ List_6 @ A_6 @ Exp2_8 )
     != ( fAss_list_char @ Exp1_7 @ List1_3 @ List2_3 @ Exp2_7 ) ) )).

thf(fact_156_exp_Osimps_I182_J,axiom,(
    ! [Exp1_6: exp_list_char,List1_2: list_char,List2_2: list_char,Exp2_6: exp_list_char,Exp1_5: exp_list_char,List_5: list_char,A_5: list_char,Exp2_5: exp_list_char] :
      ( ( fAss_list_char @ Exp1_6 @ List1_2 @ List2_2 @ Exp2_6 )
     != ( tryCatch_list_char @ Exp1_5 @ List_5 @ A_5 @ Exp2_5 ) ) )).

thf(fact_157_exp_Osimps_I169_J,axiom,(
    ! [Exp1_4: exp_list_char,List_4: list_char,A_4: list_char,Exp2_4: exp_list_char,Exp_4: exp_list_char,List1_1: list_char,List2_1: list_char] :
      ( ( tryCatch_list_char @ Exp1_4 @ List_4 @ A_4 @ Exp2_4 )
     != ( fAcc_list_char @ Exp_4 @ List1_1 @ List2_1 ) ) )).

thf(fact_158_exp_Osimps_I168_J,axiom,(
    ! [Exp_3: exp_list_char,List1: list_char,List2: list_char,Exp1_3: exp_list_char,List_3: list_char,A_3: list_char,Exp2_3: exp_list_char] :
      ( ( fAcc_list_char @ Exp_3 @ List1 @ List2 )
     != ( tryCatch_list_char @ Exp1_3 @ List_3 @ A_3 @ Exp2_3 ) ) )).

thf(fact_159_exp_Osimps_I15_J,axiom,(
    ! [Exp1_2: exp_list_char,List_2: list_char,A_2: list_char,Exp2_2: exp_list_char,Exp1_1: exp_list_char,List_1: list_char,A_1: list_char,Exp2_1: exp_list_char] :
      ( ( ( tryCatch_list_char @ Exp1_2 @ List_2 @ A_2 @ Exp2_2 )
        = ( tryCatch_list_char @ Exp1_1 @ List_1 @ A_1 @ Exp2_1 ) )
    <=> ( ( Exp1_2 = Exp1_1 )
        & ( List_2 = List_1 )
        & ( A_2 = A_1 )
        & ( Exp2_2 = Exp2_1 ) ) ) )).

thf(fact_160_exp_Osimps_I14_J,axiom,(
    ! [Exp_2: exp_list_char,Exp_1: exp_list_char] :
      ( ( ( throw_list_char @ Exp_2 )
        = ( throw_list_char @ Exp_1 ) )
    <=> ( Exp_2 = Exp_1 ) ) )).

thf(fact_161_exp_Osimps_I225_J,axiom,(
    ! [Exp1: exp_list_char,List: list_char,A: list_char,Exp2: exp_list_char,Exp: exp_list_char] :
      ( ( tryCatch_list_char @ Exp1 @ List @ A @ Exp2 )
     != ( throw_list_char @ Exp ) ) )).

%----Conjectures (1)
thf(conj_0,conjecture,
    ( wTrt @ p @ h_a @ e @ e_a @ nt )).

%------------------------------------------------------------------------------
